### ISSUE TITLE
Unable to style using `headerProps` / `rowProps`

### ISSUE THREAD

**Issue by nemoDreamer** [Autodesk/react-base-table#100]
The way `headerProps` / `rowProps` is treated makes it had to add simple styling to BaseTable.

We can't use SCSS, as we use CSS-in-JS to provide themes values to our Components.
Right now, since the default `headerRenderer` isn't accessible via `BaseTable.defaultProps.headerRenderer`, we can't easily decorate its output, but have to manually re-create it given only the `cells`:

```jsx
const defaultHeaderRenderer = ({ cells /* , columns, headerIndex */ }) =>
    <StyleSheet styles={styles} useDesignLanguageContext>
        {({ styleSheet }) =>
            cells.map(cell =>
                React.cloneElement(cell, {
                    style: {
                        ...(cell.props.style || {}),
                        ...styleSheet.headerCell,
                    },
                })
            )}
    </StyleSheet>;
```

We'd love to be able to simply supply `style` as part of `headerProps`:

```
<BaseTable
  headerProps={{
    style: styleSheet.header,
  }}
/>
```

But it's getting overridden:
https://github.com/Autodesk/react-base-table/blob/f0f8d5621154341a9422abddec671ca8e2279785/src/BaseTable.js#L354-L366

Are we missing a way to do this using the main `style` prop? Can this prop be nested?
Or should I supply a pull-request to merge `extraProps.style with `headerProps`'s `style`?

**Comment by nemoDreamer** [comment]
The same is happening for `headerCellProps` / `cellProps`:

https://github.com/Autodesk/react-base-table/blob/f0f8d5621154341a9422abddec671ca8e2279785/src/BaseTable.js#L412-L424

**Comment by nemoDreamer** [comment]
On a related note: is there any plan to make this part of the HIG, or be able to consume HIG's theme data? 🤞

**Comment by nihgwu** [comment]
hey @nemoDreamer , it's by design to not consume `style` from external source, as it's easy to invalidate the shallow equal check for pure component, which will make the performance optimization useless, and it's easy to override the essential style from user land, so I suggest to  className to style the elements, `rowClassName` for `BaseTable` and `className` for `Column`.

if you are using CSS-In-JS, like `styled-components`, you can style the table via `className` as well, like (you can change the class prefix via `classPrefix` too)
```
const StyledTable = styled(BaseTable)`
  .BaseTable__row {}
  .BaseTable__header-row {}
  .BaseTable__cell {}
`

There are some teams are using HIG's theme data in BaseTable, feel free to ping me on Slack so I can provide more information about that

**Comment by nemoDreamer** [comment]
@nihgwu our CSS-in-JS is inline styles, not Styled Components, because we need to serve to different non-browser environments like Sketch where we don't have the ability to inject a SCSS/CSS stylesheet. Hence the need for accessing `style`.

I'll ping you on Slack.
