### ISSUE TITLE
Is it possible to scroll to row & column? 

### ISSUE THREAD

**Issue by xaun** [Autodesk/react-base-table#101]
Ideal:
```
tableRef.scrollToItem({
          align: 'smart',
          columnIndex: colIndex,
          rowIndex: rowIndex
})
```

If not, how can I calculate the offset of a row cells horizontal position for a dynamic (columns / rows can be addded and removed) fixed table?

**Comment by nihgwu** [comment]
there is [scrollToRow](https://autodesk.github.io/react-base-table/api/basetable#methods-scrollToRow(rowIndex, align)), if you want to to scroll to a cell horizontally, you can use `scrollToLeft(scrollLeft)` or `scrollToPosition({ scrollTop, scrollLeft })`

For a fixed table, you can always know the width of each column, if you don't resize the columns, they keep the value you set at the beginning, or you can sync them via `onColumnResize`, or `ref.getColumnManager().getVisibleColumns()` to get the visible columns, and then you will get everything about the internal columns

**Comment by nihgwu** [comment]
The idea is that a table is a list rather than a grid, so we didn't provide the interface as the Grid from `react-window` does, although we are using Grid to implement the table, but in the next version, I'll use List instead

**Comment by xaun** [comment]
Ok, yep I just got it working with scrollToRow and scrollToLeft - not quite as succinct but understandable re: `List`, thanks for the info.
