### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by pocesar** [Autodesk/react-base-table#103]
since the library had no typings and my project has all the strict options enabled, I would not be able to use the component properly, so I went ahead and did the bare minimum I needed for the Typescript typings

https://gist.github.com/pocesar/5b515d0e1eb8e668ec9f34b6b1412515

feel free to either integrate into the project or just ignore it (some other people might find useful though)

**Comment by nihgwu** [comment]
Hey @pocesar thanks for your sharing, there are already 3 PRs there for typescript typings, I don't have enough time to go over with them right now, I'll start the work the next week.

**Comment by pocesar** [comment]
oh my bad, should have checked before 😢
