### ISSUE TITLE
cellRenderer function is always executed when hover the table?

### ISSUE THREAD

**Issue by JtCheung** [Autodesk/react-base-table#104]
@nihgwu Hi, you guys really did a great job, react-base-table is an amazing table. I love it.
I found a problem that when I hover the cells, the cellRenderer function will always be executed, I'm not very sure if this will create some performance issues. Is there any way to fix this or just ignore this problem. thanks!

**Comment by nihgwu** [comment]
I don't think that would be a problem, as the hovering will only make two rows re-rendered to apply the hovering style when `fixed={true}` in a short time, what will effect the performance badly is rendering lots of rows in the same time when scrolling.

It's cheap to call the `cellRenderer` function, if nothing changed it won't effect the performance at all, and you can memoize the renderer to avoid unnecessary re-rendering, also I think `dataKey` and `dataGetter and a custom `components.TableCell` would satisfy most of the use cases

Also it's recommended to create sharable renderers outside of the columns definition, for example
```
const IconCell = ({ cellData }) => <Icon name={cellData} />
// and you can use React.memo for complex cell
const IconCell = React.memo(...);
```
