### ISSUE TITLE
why does it work worse in ios app

### ISSUE THREAD

**Issue by ClearTrajectory** [Autodesk/react-base-table#105]
Like Custom RowKey component,  it will be show only one page of  data , then move screen, it will be blank around it.   Most of the time,  eight seconds later, it will be.

**Comment by nihgwu** [comment]
I'd say BaseTable is specially optimized on Chrome than other browsers, for the issue you described is hard to fix with virtualize rendering

**Comment by ClearTrajectory** [comment]
Thank you for your help. I agree with your point of view, but i didn't describe my issue, what confused me is that it can perform very well in Android app, Chrome, and Safari, Is it because the kernel is different? Thanks again!

**Comment by nihgwu** [comment]
It perform best on Chrome, it would be junky when scrolling with complex cells even on Safari/macOS, for Safari/iOS, and I guess the momentum scrolling makes the situation worse
