### ISSUE TITLE
Data Not Rendering

### ISSUE THREAD

**Issue by mzacharcc** [Autodesk/react-base-table#113]
I created a project using the same code from the default example table and react-base-table v1.9.1, and it could not find the data using dataKeys unless I overrode the getters.  I rolled back to v1.6.5 (which I have working in a different project) and the data rendered using the default getters.

Edit: Just checked, it works fine in 1.9.0.

**Comment by nihgwu** [comment]
Could you share a reproducible demo or playground, thanks

**Comment by nihgwu** [comment]
https://github.com/Autodesk/react-base-table/pull/109/files this is the only change from v1.9.0 to v1.9.1, I don't think that would impact the dataGetter
