### ISSUE TITLE
Ability to customize row rendering a little more

### ISSUE THREAD

**Issue by nickytonline** [Autodesk/react-base-table#114]
Not the best title for an issue, but it's the best I could come up with. 😉

On the Shotgun team, we are currently using the `<BaseTable />` component. So far it has been serving our purposes, but we've encountered an issue/potential feature add that would help not just us, but anyone using `<BaseTable />`.

We currently are using the `rowRenderer` prop with our custom row renderer. This all works fine. The issue we are currently encountering for three features we're working on requires that we be able to manipulate the `<TableRow />`, the component that wraps the row renderer returned components from our custom row renderer we pass in via the `rowRenderer` prop of the `<BaseTable />` component.

Here is a simplified version.

```javascript
class OurCustomComponent extends React.PureComponent {
  // ... mind blowing code

  render() {
      // ... awesome code

      return (
          <BaseTable
            rowRenderer={ourCustomRowRenderer}
            // ... more props

          />
      );
}
```

react-base-table exports the `<TableRow />` component, so my first thought was to have a custom row renderer as shown in the examples on the react-base-table site that returns a `<TableRow />` component with our cells constructed how we currently build them in the row renderer and this way I would be able to add custom props to the `<TableRow />` component, e.g. adding unique row data as an attribute on the rendered DOM, e.g. `data-my-attribute="someValueBuiltFromRowData"`.

However, `<TableRow />` expects certain props, the main one that is an issue for us is the `expandIconRenderer` prop. I could pass this in with some other pertinent props, but then I am essentially copy/pasting the body of the `renderRow` method of the `<BaseTable />` component.

https://github.com/Autodesk/react-base-table/blob/master/src/BaseTable.tsx#L836

I can do this, but this is a hack because I am copying internals and tweaking them as needed. What would make more sense is exposing a hook (not a React hook 😉) that would allow a consumer of the `<BaseTable>` to pass in a custom set of props pertinent to the current row. A function prop would do the trick.

I am aware of the `rowProps` prop available on `<BaseTable />`, but this prop is a set of generic row props that apply to every row without any sense of the data being rendered in the row.

Although a lot cleaner, I could add custom attributes directly on the DOM in the `componentDidMount`/`componentDidUpdate` lifecycle methods or via the `useEffect` hook.

Is this something you would consider adding? I would be happy to provide a PR showing how I see it playing out.

Thanks again for all your work on react-base-table!

**Comment by nihgwu** [comment]
@nickytonline sorry for the late response, I think your requirement could be achieved by current API if I understand it clearly. We do add `data-testid` to rows and cells in our internal table, via `rowProps` and `cellProps`, those extraProps receives both object and callback, so you can attach any props to the rows and cells, the `extraProps` api is really powerful when you realize it, for example, you can pass any props to the `ExpandIcon` combined with the `components` api, see https://autodesk.github.io/react-base-table/examples/expand-icon-props

**Comment by nihgwu** [comment]
https://github.com/Autodesk/react-base-table/pull/115#discussion_r344082968
![image](https://user-images.githubusercontent.com/2595058/68465828-2b934d80-024e-11ea-8083-f59678f99cd9.png)

**Comment by nickytonline** [comment]
I know we spoke on Slack at work, but just confirming that using the `rowProps` prop is what I needed. I don't know how I missed that it was a callback returning props and not just an object of props. Thanks again for the quick reply @nihgwu!
