### ISSUE TITLE
Customize the cell with a dropdown button, and the pop-up  dropdown list will be blocked with other cells.

### ISSUE THREAD

**Issue by xiaorui0328** [Autodesk/react-base-table#116]
Customize the cell with a dropdown button, and the pop-up  dropdown list will be blocked with other cells.
dropdownlist css already with z-index property as below:
    position: absolute;
    display: flex;
    z-index: 99;

**Comment by nihgwu** [comment]
it's expected, as all the cells/rows have `overflow: hidden`, you have to use something like `Portal` to render the dropdown outside of the rows, like this example https://autodesk.github.io/react-base-table/examples/inline-editing
