### ISSUE TITLE
ColumnResizer not exported

### ISSUE THREAD

**Issue by jeremy-christian** [Autodesk/react-base-table#117]
ColumnResizer defined in API but not exported in index, cannot incorporate into `headerRenderer` to easily resize custom columns.

**Comment by nihgwu** [comment]
ColumnResizer should not be exported, if you need the similar functionality, you can build your own one, or if you do want to use the one from BaseTable, I think you can import it from `react-base-table/lib/ColumnResizer`

**Comment by jeremy-christian** [comment]
Thank you!
