### ISSUE TITLE
overscanColumnCount Prop?

### ISSUE THREAD

**Issue by mattrothenberg** [Autodesk/react-base-table#118]
I'm curious if you all have considered exposing an `overscanColumnCount` prop that gives users finer-grained control over how columns (instead of rows) are virtualized?

The `overscanRowCount` has come in handy, though I'm running into a performance issue where, given a table of 20+ columns, resizing individual columns gets _very_ slow/janky. And an obvious improvement here would be rendering only the columns that are visible in the viewport at a given time.

Does adding such a prop sound like a natural evolution of this library? Or perhaps I'm thinking about this problem (and the proposed solution) wrong?

Thanks!

**Comment by nihgwu** [comment]
related to #36 I'll consider about this feature in the next version, but currently we treat all the columns as a single column for `react-window`'s `Grid`

Regarding the performance issue for column resizing, I would change the resizing behavior to only resize the body on drag end, which should make the ux better

**Comment by mattrothenberg** [comment]
Thanks @nihgwu , makes sense to me.

Currently, the resizing behavior _is_ hooked up to `onColumnResizeEndfuncdefaults`. Essentially, I store an array of integers in a global store that correspond to my table columns' widths, and update that array when dragging ends.

I'm noticing that it's not the _store_ updating on drag end that's causing the jank. It's literally as the user drags and the underlying DOM nodes (e.g., `BaseTable__header-`) increasing in size / changing in style.

It'd be nice if the actual "resizing" only took place when a user releases their mouse, not as they drag back and forth.

Let me know if that makes sense!

**Comment by nihgwu** [comment]
Hey @mattrothenberg your suggestion is exactly what I proposed, the constant dragging only resize the header, the body's cells will be resized only drag ended

The current resizing behavior is confusing when `fixed={false}` as the column's size doesn't stick to the drag distance because the column's width is flex not fixed, that's why I always doubt and regret making the current resizing behavior as default

**Comment by mattrothenberg** [comment]
Gotcha, apologies for misunderstanding!

Thanks for your feedback.
