### ISSUE TITLE
Feature request: The table should support keyboard navigation for cells

### ISSUE THREAD

**Issue by sapanti** [Autodesk/react-base-table#119]

**Comment by nihgwu** [comment]
you can add `tabIndex` to cells via `cellProps`, https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZizbhocHPHgAFAiAAOEPgG8YUIgCMAkmE44AHgC4YDGAF8ld3SAJccAMyKI8LA0TBgAfDAAPAAq5vA4cJSSEOiGEtQuMNymqdlEmcDqWjr6qYUa2noQmQD0YSxAA

I don't make it default as we only add tabIndex to particular cells via `cellRender` for inline editing
