### ISSUE TITLE
Too many pinned columns will cover whole table

### ISSUE THREAD

**Issue by zongUMR** [Autodesk/react-base-table#122]
If you pin many columns,  that the pinned columns will cover whole table, so you cant see the unpinned table and even you can't see the all pinned columns. 
Can someone tell me how to deal with such situation?

**Comment by nihgwu** [comment]
It's the consumer to freeze the columns, so the consumer should take care of the total width of the frozen columns, it's recommended to freeze 3 or less columns in practice, check the screenshot in the README, we have a settings panel to freeze/unfreeze columns
