### ISSUE TITLE
Question: How to make flexible column width?

### ISSUE THREAD

**Issue by zhaoyao91** [Autodesk/react-base-table#123]
For example, if a column is marked as `fit-content`, its width is just the same as its content, and the maxWidth may be helped to limit the boundary.

**Comment by nihgwu** [comment]
there is no such feature, because of memoization, the table only renders visible rows, if with the current rows, the max width of the cell is 100, what if I scroll down and there is a cell with a width of 200?

**Comment by zhaoyao91** [comment]
> there is no such feature, because of memoization, the table only renders visible rows, if with the current rows, the max width of the cell is 100, what if I scroll down and there is a cell with a width of 200?

It reasons. How about wrap lines within a cell? Currently I only see one line per cell and didn't find a prop to control it.

**Comment by nihgwu** [comment]
BaseTable doesn't support dynamic row height either, this feature is on the planning list
