### ISSUE TITLE
Is it possible to have the last row of the table fixed?

### ISSUE THREAD

**Issue by VigneshSubramaniam** [Autodesk/react-base-table#125]
Hi @nihgwu , I'm loving his Table and it provides almost all the required features. One question though. There's a custom footer option provided. But it's not scrolling if we have horizontal scroll/fixed left columns inside the table. Is it possible to have something of that sort? Let's say i have 1000 rows and the last row is total. I want that to be displayed always. Any help would be appreciated. Thanks!

**Comment by nihgwu** [comment]
@VigneshSubramaniam I'd say that's impossible with the current BaseTable. In our products we use the first row(frozen) to show aggregate data, there are some reasons to not support that, but I can't remember now(maybe weird visual behavior)

**Comment by VigneshSubramaniam** [comment]
Normally we show the total value in the last row right? Something like this.
<img width="484" alt="Screen Shot 2020-01-04 at 9 16 31 PM" src="https://user-images.githubusercontent.com/22591847/71767929-994eb380-2f37-11ea-9ec1-9fc7cb443421.png">

But the current component does not scale as expected. Any suggestions?

**Comment by nihgwu** [comment]
I totally understand your use case, in that case you have to use two tables, but there would be visual problem with the horizontal scrollbar, here is how it behaves in our products https://blogs.autodesk.com/bim360-release-notes/2019/11/18/bim-360-cost-management-update-november-2019/

**Comment by VigneshSubramaniam** [comment]
I see. I sat through and wrote a footerRenderer to solve my use case and it's working fine. Scrollbar needs to be fixed though. But that's okay for now. Cheers!! :)

While i was playing around, i realised that all the columns are rendered and it's not the same behaviour as rows? It's reducing the performance :( Should I raise a separate issue or is that being implemented?

**Comment by nihgwu** [comment]
for columns virtualization, there is an issue already #36

**Comment by danielwyb** [comment]
@VigneshSubramaniam Could you explain how you implemented the custom footerRenderer? I'm trying to add support for frozen columns on the left and scrollable columns on the right, that stay in sync with the other columns as a footer.

**Comment by mmahalwy** [comment]
@danielwyb any luck with this?

**Comment by danielwyb** [comment]
Yes @mmahalwy. Did you find one or do you need input?

**Comment by nchartiot** [comment]
@danielwyb could you provide some info or gist on how you got this working? I'm trying to deal with the different widths of each column to align the footer elements
