### ISSUE TITLE
Clicking column headers selects their text

### ISSUE THREAD

**Issue by dandv** [Autodesk/react-base-table#126]
Same bug as [here](https://github.com/tannerlinsley/react-table/issues/1850). Comes with reinventing the wheel.

![image](https://user-images.githubusercontent.com/33569/72386404-1defbd80-3700-11ea-8fdf-1fbf888a72f1.png)

**Comment by nihgwu** [comment]
I won't take it as a bug, the idea is that sometimes we won't copy the header, if you don't to select the text on double click, set `user-select: none` on `BaseTable__header-cell-text`
