### ISSUE TITLE
width and height of the table with the scrollbar

### ISSUE THREAD

**Issue by alex-gla** [Autodesk/react-base-table#128]
Good day everyone,
when we use `AutoResizer` it returns the width and height of the table with the scrollbar. 

Is there any way to obtain the length of the table without scrollbar?

**Comment by nihgwu** [comment]
I don't understand the use case, `AutoResizer` measures the container's size, the table could or not have scrollbar depending on the data, and the scrollbars only display in the table's body, you can use `utils.getScrollbarSize` to the the scrollbar's size, and `ref. getTotalRowsHeight` `ref. getTotalColumnsWidth` to get related dimensions
