### ISSUE TITLE
It is possible to resize rows? 

### ISSUE THREAD

**Issue by JtCheung** [Autodesk/react-base-table#130]
@nihgwu 
As you mention,  there is no solution for dynamic row heights right now. 
So I wonder that if there is a solution for resizing the rows manually like the demo shows how to resize columns do [here](https://autodesk.github.io/react-base-table/examples/resizable)? 
This is the situation: 
If I have to show a very long text in row, currently it shows with ...(text ellipsis) and tooltip. 
I want users can resize the row for adjusting height to see the whole text. Or how can I achieve this by other ways?

**Comment by nihgwu** [comment]
I'd say there is no way to do that as the `rowHeight` can't be a function

**Comment by nihgwu** [comment]
it support as a function before, but I thought it's to heavy to calculate the total row heights with expansion feature, so I removed the support

**Comment by 7zf001** [comment]
Hello. I want to ask a question, I want to achieve a different fixed row height, what should I do?

**Comment by jamesonhill** [comment]
@7zf001 I was able to accomplish dynamic row heights by forking the project. If you fork & switch react-base-table from using the `FixedSizeGrid` from `react-window` to `VariableSizeGrid`, you can accomplish it using this example approach: https://codesandbox.io/s/dynamic-size-of-react-window-list-items-1dwg6?file=/src/Chat.js 
I found a variant of that in a react-window issue and augmented it to work for this use case. Hope that helps.
