### ISSUE TITLE
Question: How to personalize each ".BaseTable__row-cell" style according with its value?

### ISSUE THREAD

**Issue by daniellycosta** [Autodesk/react-base-table#131]
I'd like to change de cell style according to its value. I tried to customize the TableCell component, but it didn't change the whole cell as you can see in the picture below. 

![Customized TableCell](https://user-images.githubusercontent.com/29708442/74872367-dcc07e00-533b-11ea-84d3-0c2a9854098b.png)

Instead, I'd like to obtain the result like in the next image, but I don't know how to access each cell
![image](https://user-images.githubusercontent.com/29708442/74872932-f1e9dc80-533c-11ea-99e3-a6e6e8cfc959.png)

#### Suggestion

If this feature doesn't exist, maybe create a new prop for override `.BaseTable__row-cell` CSS class could be an option like the example below.

``` javascript
	<BaseTable
           columns={tableColumns}
	   data={dataExample}
           //... other props
					
	   rowCellClassName={({ cellData }) => {
		return classnames(classes.default, {
		[classes.low]: cellData <= 20,
		[classes.mediumLow]: cellData > 20 && cellData <= 40,
		[classes.medium]: cellData > 40 && cellData <= 60,
	        [classes.mediumHigh]: cellData > 60 && cellData <= 80,
		[classes.high]: cellData > 80
                                      })
          }}
	/>
```

**Comment by nihgwu** [comment]
hey, you can use `Column.className`, it could be a callback

**Comment by nihgwu** [comment]
https://autodesk.github.io/react-base-table/api/column

**Comment by daniellycosta** [comment]
Can I access the column props using BaseTable component? I'm not using Column component

**Comment by daniellycosta** [comment]
I got it!!

I manipulated the column array adding the className props before passing it to the BaseTable component. Thank you for the quick response!!

```javascript
const getClasses = ({ cellData }) =>
		classnames(classes.default, {
			[classes.low]: cellData < 20,
			[classes.mediumLow]: cellData > 20 && cellData <= 40,
			[classes.medium]: cellData > 40 && cellData <= 60,
			[classes.mediumHigh]: cellData > 60 && cellData <= 80,
			[classes.high]: cellData > 80
		})

	const columnsWithClasses = tableColumns.map(column => ({
		...column,
		className: getClasses
	}))

//...more code

	<BaseTable
		//...more props
		columns={columnsWithClasses}
		data={dataExample}
		className={classes.table}
		
	/>

```

**Comment by nihgwu** [comment]
Or you can use it this way:
```js
<BaseTable>
  <Column key className />
</BaseTable>
```
