### ISSUE TITLE
Is it possible to turn off smooth scrolling animations for user interaction?

### ISSUE THREAD

**Issue by mdakovac** [Autodesk/react-base-table#137]
Default behaviour:
![smooth scroll](https://user-images.githubusercontent.com/30108218/77225775-a3657300-6b72-11ea-834d-a9c0f401349d.gif)

What I need:
![snap scroll](https://user-images.githubusercontent.com/30108218/77225789-d3ad1180-6b72-11ea-980c-6408450aa25f.gif)

Is it possible to use a "snapping" scroll mode, same as when using scrollToTop() when a user scrolls using a mouse/touchpad?

**Comment by nihgwu** [comment]
that's interesting, why don't you need scroll animation on mouse scroll? Perhaps you can capture the scroll event and call `scrollToTop` manually

**Comment by mdakovac** [comment]
I find that it's more performant that way, because I have many custom cells, and rows can sometimes render slowly, leaving white space at the top/bottom of the table when scrolling up/down. 

Could you show an example? I have tried this using the onScroll prop on the table, but it doesn't seem to work

**Comment by nihgwu** [comment]
I'd say there are tradeoffs for performance with large dataset, it's not caused by the smooth scrolling, but I'm think there should be no white space while scrolling on Chrome

**Comment by philxavier** [comment]
I'm actually looking for a way to do the opposite: go from "snapping" mode to "smooth" mode when I use scroll methods. Anyone has an idea about it?

**Comment by nihgwu** [comment]
@philxavier you can use requestAnimationFrame to scroll step by step, see https://github.com/bvaughn/react-window/issues/16
