### ISSUE TITLE
Scroll bar is out of sync when data is long

### ISSUE THREAD

**Issue by Grafaceio** [Autodesk/react-base-table#139]
Scroll bar is out of sync when data is long and set Frozen Rows

**Comment by nihgwu** [comment]
I'd say that's the tradeoff for the current implementation, will make it better in the next version

**Comment by Grafaceio** [comment]
like this [](https://codesandbox.io/s/nameless-sun-bsxjz?file=/index.js), on react-window onmousewheel event have deley

**Comment by Grafaceio** [comment]
[https://codesandbox.io/s/nameless-sun-bsxjz?file=/index.js](https://codesandbox.io/s/nameless-sun-bsxjz?file=/index.js)

**Comment by Grafaceio** [comment]
![222](https://user-images.githubusercontent.com/13866430/81779333-1661e900-9527-11ea-9a53-332e97bab97e.gif)

**Comment by nihgwu** [comment]
I under stand the problem here, I did some tricks for Chrome, so you won't see the scroll lag on Chrome 😄
