### ISSUE TITLE
Expand a row and render a custom component within it

### ISSUE THREAD

**Issue by vcardins** [Autodesk/react-base-table#140]
I'd like to be able to expand a row by clicking on a custom action and load a custom component within it. The expanded row would have `colspan` = # of columns. Just like the picture below.

![image](https://user-images.githubusercontent.com/2383329/77801848-e32acf80-7036-11ea-942c-705b36041a64.png)

Thank in advance for the support

**Comment by nihgwu** [comment]
https://autodesk.github.io/react-base-table/examples/row-renderer or https://autodesk.github.io/react-base-table/examples/row-span

**Comment by jasontll** [comment]
> https://autodesk.github.io/react-base-table/examples/row-renderer or https://autodesk.github.io/react-base-table/examples/row-span

The row height is styled and fixed for every rows, there's no way to expand it dynamically. I tried using the row renderer method, and my content ends up being cut off or overflow to next row because the height are fixed.

**Comment by nihgwu** [comment]
Ahh, now I understand your requirement here, currently BaseTable doesn't support variable row height, so display an expanded row with a different height is not able to implement, I did implement that feature in BaseTable before but removed that later

**Comment by jasontll** [comment]
Since the data will displayed in the expanded row will be pulled remotely, I am planning to just show it in the custom overlay for now. @nihgwu why is the feature being removed? Do you plan on re-implementing expanded row custom content feature anytime? Good job on the package by the way.

**Comment by nihgwu** [comment]
For expanded row, you have to provide the row height explicitly, so `rowHeight` should be a function, just like the `VariableList` in `react-window`, but I think that would limit the usage as sometimes we just don't know the exact height for the expanded area, so the best solution for this scenario should be the `DynamicList` in `react-window`, but that component is still working in progress(for quite a long time), so I'm planning to implement the dynamic list by myself, but I just don't have enough time on it right now

**Comment by Michael101sh** [comment]
Hi @nihgwu ,
I would very happy if you pleasee will add this feature, means that it is possible to insert a variable height custom component and not necessarily 50 height, and that the table behaves properly, meaning that the rows below will get down and start at the end of this component and that it will work well with (vertical) scrolling.

**Comment by nihgwu** [comment]
OK, thanks #170, it is possible now, here is an example http://localhost:8001/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZixbcoRAHQAzEAQCiRYAAsaADwwA+GAG8WMGMbWGAlvE4E8fANo3bV7z5iOnABcMAAGACSW9oEAvgC0nDiqzqFSfj7spGBQIRpEANaEavDaOMhqAA5ExFjEFQa0TGn+Mc0wALosMaxs4NAwAOIlAEZE8ADKUACe8Dh8wG5CQyCjE9Ozod5qAEJEEDgAKkTDswD6pwQgAO5xCTgVUAZxDL7+BjiOWAY5MACsDBVjABubwxFibXocGAAJWufGgMxwnDUnEcADdNrYqpxUWAsCE6L9ASDNux+pcrtC8Ik3AQ+DRLDAKaJVDJgDh4PAIDBuuZXgENDAaMyeA5wFkoEwmUlEAQwDAADywq5mSwi1Ri7J4KAxBUAemVZm8bigsvl7M5EC6Shwxgq2i4ODyiHgsBoUvQFho3gVRv8CuWq0miJger9PgVRxOOHStg0jmMSNjMFtVTAnAoVDAAGkcFN0JYJNQPAx2mpClMwf5bDhoI5kEJOMqABIfL5QAv-KvVouQAu9iDd-wqIgFkdDnwUqnpwiEAtT6mzggTsM+1esIA

Be sure it won't work with frozen columns, and there is a minor bug with flex mode(the scrollbar width is not synced properly), I'll create a PR to fix it soon
