### ISSUE TITLE
How to refresh the table when data changes?

### ISSUE THREAD

**Issue by mike-lischke** [Autodesk/react-base-table#142]
Just a quick question: how would I refresh the table after something in the data changed? React doesn't see the change and hence doesn't re-render the table.

Thanks for an awesome component!

**Comment by nihgwu** [comment]
the table will refresh if the data changed, please note that you have to change the reference of the data, not muting the data directly, that means `newData=[...data, newRow]` instead of `data.push(newRow)`, also for the row data, you have to create a new object, `newData=[..., {...rowX, changed}, ...]`

**Comment by mike-lischke** [comment]
Thanks for the quick reply. That's what I do actually. I create a new `data` array and call `this.setState` with, effectively replacing the stored data. `render()` gets the new data, but the table doesn't update. Pretty weird...

**Comment by nihgwu** [comment]
can your provide a reproducible demo, like here https://autodesk.github.io/react-base-table/playground/ and share the url

**Comment by mike-lischke** [comment]
While creating a demo for you I saw that updates happened correctly, so it was clear there must be something different wrong in my original code. Then I found that I don't use the react lifecycle properly. After switching to `getDerivedStateFromProps` for my sub components they started to update properly as well.

Thanks anyway for trying to help!

**Comment by raghuveerd** [comment]
hi @mike-lischke 
I am facing the exact same issue. A user action updates the row data and add a new row. The new row is getting rendered by not updating the updated-existing-row. 
Can you please give some pointer on how you used the `getDerivedStateFromProps `to fix your issue.

**Comment by nihgwu** [comment]
@raghuveerd how do you update the existing row data? Or you can write up a simple demo in the playground

**Comment by raghuveerd** [comment]
> @raghuveerd how do you update the existing row data? Or you can write up a simple demo in the playground

I will try to put up an example, it seems the rowId  which would form the key needs to be changed so that the existing row data is updated.  That was the solution which I tried and it seem to work.
Might not be the right one.. but I haven't been able to use `getDerivedStateFromProps ` as suggested.

**Comment by nihgwu** [comment]
@raghuveerd you don't need to change the rowid if you only want to update the other parts of the row, you just need to make sure you change the reference of the rowData and data
