### ISSUE TITLE
User must hover over row before data is updated

### ISSUE THREAD

**Issue by hypersurface** [Autodesk/react-base-table#145]
I've added a material-ui checkbox cell to each row in column 1 of my table, including a similar checkbox for the table header. If I click on the checkbox in a given row, then it checks as expected. I also added the ability to click the checkbox in the header and have all of the rows checked. However, after clicking on the checkbox in the header I have to hover over the rows in order to see that that checkboxes have been checked. Is this a bug with the rendering of react-base-table? Is there a way to force the table to re-render?

**Comment by nihgwu** [comment]
the reason is that the row will rerender only if the rowData changed or the column definition changed, so if you can pass the selectedRowKeys state to one of the column definition, typically the selection column, then it should work as expected

**Comment by hypersurface** [comment]
I'm updating the state of the rowData but I still have to hover over each row before the update is reflected in the UI:
     `<AutoResizer>
                 {({ width, height }) => (
                        <Table
                            fixed
                            width={width}
                            height={height}
                            columns={state.columns}
                            data={state.rows}
                            sortBy={state.sortBy}
                            onColumnSort={onColumnSort}
                            onColumnResize={resizeColumn}
                            onColumnResizeEnd={resizeColumnEnd}
                            components={components}
                        />
                 )}
     </AutoResizer>`

Can you please clarify what you mean by "pass the selectedRowKeys state to one of the column definition"?

**Comment by nihgwu** [comment]
have you read this  and https://autodesk.github.io/react-base-table/examples/selection, 
```js
      const selectionColumn = {
        width: 40,
        flexShrink: 0,
        resizable: false,
        frozen: Column.FrozenDirection.LEFT,
        cellRenderer: SelectionCell,
        ...selectionColumnProps,
        key: '__selection__',
        rowKey: this.props.rowKey,
        selectedRowKeys: selectedRowKeys, // pass selectedRowKeys state to the column definition
        onChange: this._handleSelectChange,
      }
```
