### ISSUE TITLE
frozenData not shown when data is an empty array

### ISSUE THREAD

**Issue by kachkaev** [Autodesk/react-base-table#146]
👋 Hey @nihgwu and other folks! This is a truly awesome library, I hope it’ll properly jet off in the community! 🚀

Here is a small bug I just discovered:

1. Open this example: https://autodesk.github.io/react-base-table/examples/frozen-rows

2.  Tweak it

    ```diff
      const columns = generateColumns(10)
    - const data = generateData(columns, 200)
    + const data = generateData(columns, 0)
      const frozenData = generateData(columns, 3, 'frozen-row-')

      const fixedColumns = columns.map((column, columnIndex) => {
        let frozen
        if (columnIndex < 2) frozen = Column.FrozenDirection.LEFT
        if (columnIndex > 8) frozen = Column.FrozenDirection.RIGHT
        return { ...column, frozen }
      })

      const expandColumnKey = 'column-0'

    - // add some sub items
    - for (let i = 0; i < 3; i++) {
    -   data.push({
    -     ...data[0],
    -     id: `${data[0].id}-sub-${i}`,
    -     parentId: data[0].id,
    -     [expandColumnKey]: `Sub ${i}`,
    -   })
    -   data.push({
    -     ...data[2],
    -     id: `${data[2].id}-sub-${i}`,
    -     parentId: data[2].id,
    -     [expandColumnKey]: `Sub ${i}`,
    -   })
    -   data.push({
    -     ...data[2],
    -     id: `${data[2].id}-sub-sub-${i}`,
    -     parentId: `${data[2].id}-sub-${i}`,
    -     [expandColumnKey]: `Sub-Sub ${i}`,
    -   })
    - }

      const treeData = unflatten(data)

      export default () => (
        <Table
          fixed
          columns={fixedColumns}
          data={treeData}
          frozenData={frozenData}
          expandColumnKey={expandColumnKey}
        />
      )
    ```

3.  Observe frozenRows disappearing as well as non-frozen ones, which looks like a bug.

As a workaround, I'll try swapping treeData and frozenData when treeData is an empty array. The challenge though is to manually style a now unfrozen row the same way as `BaseTable__row--frozen` (I made those look almost like header cells)

**Comment by nihgwu** [comment]
hi @kachkaev yes that's a bug https://github.com/Autodesk/react-base-table/blob/master/src/BaseTable.js#L584, a better workaround is making `BaseTable__empty-layer` display none if you have frozen data but no data, but I'll release a new version to fix it, thanks for the report

**Comment by kachkaev** [comment]
Terrific, many thanks for such a quick patch @nihgwu  🙌

**Comment by kachkaev** [comment]
Just noticed that the playground (https://autodesk.github.io/react-base-table/examples/frozen-rows) points to 1.9.1, could you redeploy when you have time?

**Comment by nihgwu** [comment]
redeployed
