### ISSUE TITLE
Unable to horizontally scroll frozen rows (and header rows)

### ISSUE THREAD

**Issue by kachkaev** [Autodesk/react-base-table#148]
👋 hi agian @nihgwu! Here is one more small discovery to share.

Seems like horizontal does not work when the cursor is above a frozen row or a header row:
https://autodesk.github.io/react-base-table/examples/frozen-rows

![Kapture 2020-04-24 at 9 19 29](https://user-images.githubusercontent.com/608862/80190835-c91be700-860c-11ea-83f6-d90a179d1306.gif)

I am using trackpad on a macbook, but I don't think that it's different to a mouse with two wheels.

This behaviour seems to apply to fixed tables that even do not have any frozen cols or rows:
https://autodesk.github.io/react-base-table/examples/fixed

WDYT?

**Comment by nihgwu** [comment]
Yes that's true, if you want to scroll header/frozen rows, there should be scrollbar under it, which is ugly, so you have to scroll on normal rows, this behavior will be fixed in the next major version which would be a rewrite

**Comment by kachkaev** [comment]
I'm wondering if it's possible to achieve the desired effect with rather little effort. What do you think of this trick:

* header has `overflow:scroll; padding-bottom:1000px; margin-bottom:1000px` and is put into an extra container
* extra container has `overflow:hidden`, which hides the horizontal scrollbar inside
* on scroll for header rows is wired up to resetting scroll offset in the normal rows (guess this will be similar to how things are done now, just in the reverse)

I have very little experience with doing custom tables, so it's quite possible that my idea is too naive and won't work. I also saw `overflow-x` / `overflow-y`, which might help here too, but never tried them myself.

WDYT?

**Comment by nihgwu** [comment]
Sorry for the late response, yes I think your idea should work, but I don't have the plan to introduce it in V1
