### ISSUE TITLE
Is it there proper document for code example?

### ISSUE THREAD

**Issue by KhadeerUI** [Autodesk/react-base-table#151]
You did a great job of awesome work. But I have some issues when I try to implement examples code not working as expected but what you showing that is working as good in your examples page. Please could you give me the code-wise document?

**Comment by nihgwu** [comment]
sorry for the confusing, for the example, all the magics are in https://github.com/Autodesk/react-base-table/blob/master/website/src/utils/baseScope.js if you are familiar with `react-live`
