### ISSUE TITLE
When row span scrolls, the merged row will be invalid

### ISSUE THREAD

**Issue by condorheroblog** [Autodesk/react-base-table#156]
In my project, seven rows of tables are required to be merged, but I found that if the row span value is greater than three, the merged row will fail when scrolling. Here's the picture: is there a solution.

![When row span scrolls, the merged row will be invalid](https://user-images.githubusercontent.com/47056890/82880572-35259e00-9f71-11ea-830f-2a8db9342227.gif)

**Comment by condorheroblog** [comment]
The code of merging three lines in the figure is the same as the code below the GIF figure

`columns[rowSpanIndex].rowSpan = ({ rowData, rowIndex }) =>
  rowIndex % 3 === 0 && rowIndex <= data.length - 3 ? 3 : 1`

If it is greater than five lines, stop scrolling, and the merged line is invalid all the time
![image](https://user-images.githubusercontent.com/47056890/82884079-d3b3fe00-9f75-11ea-8ac5-fcc143da1505.png)

When it is less than five lines, it will flash down only when rolling.

Look forward to your reply. 🙏🙏🙏

**Comment by nihgwu** [comment]
I understand  the problem here, and the reason is the merged row is recycled because of virtualization, you can set `overscanCount` to ease the problem, but it's still not ideal, it works great if you scroll down, but if you scroll up, the overscan don't works so well as expected

**Comment by bammoo** [comment]
```js
      const overscanBackward =
        !isScrolling || verticalScrollDirection === 'backward'
          ? Math.max(1, overscanCountResolved)
          : 1;
```

when isScrolling this always return 1

**Comment by StianIsmar** [comment]
> ```js
>       const overscanBackward =
>         !isScrolling || verticalScrollDirection === 'backward'
>           ? Math.max(1, overscanCountResolved)
>           : 1;
> ```

Is this a working solution for you?

**Comment by Yeenot** [comment]
@nihgwu @StianIsmar Is there any workaround on solving this flickering issue when scrolling down?

**Comment by seonghong1** [comment]
We're having the same problem Did you solve it?
If you solved it, what keywords did you use to solve it
