### ISSUE TITLE
how to achieve a different fixed row height?

### ISSUE THREAD

**Issue by 7zf001** [Autodesk/react-base-table#158]
I have studied the documentation for a long time and have no idea.
Hope to get help,
Thank you very much.

**Comment by nihgwu** [comment]
the current answer is no, but this is a work around, the `headerHeight` could be an array, so you can use the header as the fixed rows, with custom `Column.headerRenderer`

**Comment by 7zf001** [comment]
thanks~
but I thought of a method to achieve, using the method of merging rows to increase the height.
like this:
![4041591004787_ pic](https://user-images.githubusercontent.com/24474049/83397242-dd36dd80-a42f-11ea-98e4-25a28e41e156.jpg)

**Comment by qiang-chen** [comment]
请问如何merging rows

**Comment by qiang-chen** [comment]
> 


请问如何merging rows
