### ISSUE TITLE
Row with a column dedicated to buttons

### ISSUE THREAD

**Issue by jamezrin** [Autodesk/react-base-table#163]
Is it fine to store a component in the data objects? I want to add a column to the rows of the table that when clicked do some action related to that row. I'm currently doing this https://codesandbox.io/s/laughing-euler-xecf4?file=/src/App.js

Is that the right way to do it? My idea of it was that data is only for raw data and add additional columns afterwards, but I don't know exactly how.
Also, is there an example with this kinda of setup? I couldn't find anything like this on https://autodesk.github.io/react-base-table/examples/default 

Thanks!

**Comment by nihgwu** [comment]
you could do that, but not recommended, you should use `Column.cellRenderer` for complex cell or `Column.dataGetter` for text format instead, btw I just found I missed the examples for those apis, will add some later

**Comment by nihgwu** [comment]
example added in #167

**Comment by jamezrin** [comment]
Thank you so much!
