### ISSUE TITLE
How to lazily/dynamically fetch data if the number of rows is known in advance

### ISSUE THREAD

**Issue by momesana** [Autodesk/react-base-table#171]
### My use-case
I need to display a large amount of rows (upwards of 300k) where the number of rows is precalculated on the backend and passed to the frontend but where it's not viable to prefetch all the data at once before rendering the table. The backend will churn out chunks of about 2k dataItems for each request and even that takes a few seconds. Furthermore small changes to available filters will result in a completely different number of items so again prefetching and caching all the data in advance unfortunately is not an option. Paging too has been dismissed as an option given the usability drawbacks we've encountered so far with our existing solution.

### The Problem
I am having trouble coming up with an elegant solution (or the right way) to lazily/dynamically fetch the row-data once they are required (the user has scrolled those rows into view). From what I understand, react-base-table requires a `data` aray and queries both the length and the row-data from that property. There is also `dataGetter` for individual cells but as far as I can see, it too relies on an existing entry for the row-data in question. I see no easy way to tell react-base-table that there are `n` `rows` but have react-base-table query the data using a custom getter function.

### My current approach
Currently (lacking better ideas) the approach I would pursue is to pass a proxy object to react-base-table via the `data` property and return the length of the available data (which is known to us as that has been precalculated by the backend as outlined above). I would then override the `length` attribute and also provide a placeholder object when data for a row is queried that has not yet been fetched.
I would also schedule the fetching of the missing row data using the parameters passed to `onRowsRendered` and once the data has been fetched force an update using `forceTableUpdate`.

### Question
Is there a better approach?

**Comment by nihgwu** [comment]
I think instead of using Proxy which would ask you to mutate the data directly and you have to call `forceUpdateTable` manually, you can initialize the data at first, like `data = new Array(n).fill(dateItemSkeleton)` or with initial fetched data, with the data item skeleton, it won't throw error is you use `dataKey` instead of `dataGetter`, or you can use a custom `TableCell` component to do more advanced and unify the behavior, like show loading status if the rowData is a placeholder, then in `onRowsRendered` you can judge if you need a new request for the current rendered rows, when new data is fetched, you can get the new data by `data = [...startSlice, ...newData, ...endSlice]`

**Comment by momesana** [comment]
@nihgwu, I tried that and encountered the following issues:
1. using a static skeletonItem throws an error since the id's used need to be unique, so I have to resort to something like Array.from({ length: n }, (_, idx) => ({...skeletonItem, id: idx })); which makes the process even slower for really large tables (about half a million or even larger) 
2. the creation of items takes about 3 seconds for 500k items which is in fact too long but react-base-table takes considerably longer to render the items. It is prohibitively slow. I tried to use the approach with the Proxy instead and realized it too takes very long though the overhead involved in creating the proxy is negligible. I then added a print statement to the function for retrieving item-data and it turns out react-base-table repeatedly queries the item even though the item has not been scrolled into the view. If I use n = 5000, it will query the row data item for each index repeatedly.
3. resizing the columns with a large number of rows (100000) is considerably slower than doing so with a small number of rows. Again, I can see that this too is caused by the items being queried  (multiple times through the resizing process) even though that they are far from being scrolled into view.

Below is the code I used to create the proxy item:
`
    const [data, updateData] = useState(() => {
        // eslint-disable-next-line compat/compat

        const fakeData = new Proxy([], {
            get: function (target, prop, receiver) {
                if (prop === 'length') {
                    return n;
                }
                if (typeof parseInt(prop) === 'number') {
                    if (prop === '5678') {
                        console.log('item for index ', prop, ' requested');
                    }
                    return {
                        id: `salam ${prop}`,
                        state: 'mehdi jaan',
                    };
                }
            },
        });

        return fakeData;
    });
`

**Comment by momesana** [comment]
It seems to be the proptypes, that try to check the entire range which is preposterous:
![2020-06-19-155946_1171x720_scrot](https://user-images.githubusercontent.com/12494/85140949-51ea8400-b246-11ea-874d-c4f233f677cf.png)
![2020-06-19-160037_1182x568_scrot](https://user-images.githubusercontent.com/12494/85140964-56af3800-b246-11ea-81e0-b6c0985a81ee.png)
![2020-06-19-160116_1180x597_scrot](https://user-images.githubusercontent.com/12494/85140972-59119200-b246-11ea-92c7-b9843bf26e92.png)

**Comment by nihgwu** [comment]
Maybe you can use `react-window` directly, which only needs data length

**Comment by momesana** [comment]
> Maybe you can use `react-window` directly, which only needs data length

Yeah, I am already using react-window for other purposes but I wanted to have something more high level that already provides some features like column resizing and especially fixed columns and also supports trees.
I'll probably end up implementing a tree-table view from scratch.

**Comment by nihgwu** [comment]
hey @momesana thanks for your inspection, I just checked locally and you are right that the PropTypes will iterate the data, if I change `data: PropTypes.arrayOf(PropTypes.object).isRequired` to `data: PropTypes.array.isRequired`, that would be OK, and if you are fine with that I'm happy to make the change

I'd like to mention that the prop types check will be disabled in production

BTW, on my MBP it costs 0.03s to create 300k items via `const data = Array.from({ length: 300000 }, (_, idx) => ({ id: idx }))` or 0.13s via `const data = Array.from({ length: 300000 }, (_, idx) => ({ id: idx, ...shared }))`, I used `skeletonItem` to make sure `dataKey="a.b.c"` work out of box, but if you don't have those kind of `dataKey` or you use `dataGetter`, you just need to initialize with `({ id: idx })` without skeleton item

And if the total height of the rows exceeds a certain value, like 400000 items with `rowHeight=50`, when you scroll to the end, that's a know issue for `react-window` and the author doesn't want to fix(there is workaround in `react-virtualized`)

**Comment by momesana** [comment]
> hey @momesana thanks for your inspection, I just checked locally and you are right that the PropTypes will iterate the data, if I change `data: PropTypes.arrayOf(PropTypes.object).isRequired` to `data: PropTypes.array.isRequired`, that would be OK, and if you are fine with that I'm happy to make the change
> 
> I'd like to mention that the prop types check will be disabled in production
> 
> BTW, on my MBP it costs 0.03s to create 300k items via `const data = Array.from({ length: 300000 }, (_, idx) => ({ id: idx }))` or 0.13s via `const data = Array.from({ length: 300000 }, (_, idx) => ({ id: idx, ...shared }))`, I used `skeletonItem` to make sure `dataKey="a.b.c"` work out of box, but if you don't have those kind of `dataKey` or you use `dataGetter`, you just need to initialize with `({ id: idx })` without skeleton item
> 
> And if the total height of the rows exceeds a certain value see #143 , like 400000 items with `rowHeight=50`, when you scroll to the end, that's a know issue for `react-window` and the author doesn't want to fix(there is workaround in `react-virtualized`)

Hi @nihgwu, first of all thank you very much for taking the time. I really appreciate it. If changing the prop-type to just array prevents the inspection of every item that would be awesome. I must confess, I didn't test it in production yet but I suppose I would rather have it not iterate through all the items since I'll have to test it with large lists in development due to the special use case of our customers.

As for the performance, I am using a lenovo T580 with an i7. The performance also largely depends on the JavaScript engine in use and older versions are less optimized and slower. They also usually tend to be installed on older machines which doesn't really help make things better. I think the approach of having something like a "store" and being able to query the size and items from the store on the demand (which is the approach introduced by the ExtJs data grids) is more flexible than having an array but that's also something I could live with.

Regarding the height issue or rather the number of items, it's something that most libraries suffer from (again the ExtJs data grid is an exception and I am not sure how they did it). I once implemented a simple virtualized data-grid and ran into the issue as well upwards of a few hundred thousand items. The limit actually depends on the row-height. The issue (and thus the number of "reachable" items depends on the implementation specifics of the browser and is caused by the limits regarding the maximum possible height of an element in pixels (https://stackoverflow.com/questions/16637530/whats-the-maximum-pixel-value-of-css-width-and-height-properties) and how it interacts with the values and resolution of the scrollbar. You can bypass that if you don't use the native scrollbar and instead implement all of that from scratch but that means a lot of work and a lot of edge cases to take care of and an impact on performance.Therefore, I can sort of understand why the react-window maintainer refuses to implement it.

Again thanks a lot in advance for the Prop-Types fix + the hint about the prop-types checks being disabled in production. I am Looking forward to using it.
