### ISSUE TITLE
Bug:Frozen Property in a column is activating Hover on whole Table

### ISSUE THREAD

**Issue by jtaalmasco** [Autodesk/react-base-table#176]
This is the code [reproduce](https://codesandbox.io/s/quiet-hooks-gzgrj?file=/src/App.js)

The problem is substantial in a list of 1000 plus since it's activating the Hover in whole Table.

**Comment by jtaalmasco** [comment]
Just needed to add `rowKey={'idl'}` in the `<Table/>`

**Comment by kaleem-elahi** [comment]
Getting same issue, is Id a column name or it is from row data ?

**Comment by nihgwu** [comment]
@kaleem-elahi there should be unique id for each item in `data`, and it defaults to `id` but if you are using other property like `code` or `key`, you need to specific it via `rowKey`

**Comment by kaleem-elahi** [comment]
@nihgwu  Actually, I am getting an issue of Infinite scroll with Frozen columns, It doesn't work 


![image](https://user-images.githubusercontent.com/10118543/123311261-96d58480-d544-11eb-819c-eee7a2c4b93c.png)
