### ISSUE TITLE
Expanded Rows don't render before hover/scroll on 1.10.1

### ISSUE THREAD

**Issue by greggailly** [Autodesk/react-base-table#179]
### Link to codesandbox:

[![Edit React Tables](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-tables-x3vii?fontsize=14&hidenavigation=1&theme=dark)

### Bug:

When expanding rows the children rows don't render at first.
Then render on next hover / scroll.

Seems to be coming from the latest version as reverting to 1.9.4 avoids the problem.

Cheers !

**Comment by nihgwu** [comment]
@greggailly Thanks for the repro demo, seems it's a regression introduced by #170, it works with `v1.9.4`, I'll fix it soon, sorry for the inconvenience
