### ISSUE TITLE
Unselect a Single row after Select All is not Rendering instantly 

### ISSUE THREAD

**Issue by jtaalmasco** [Autodesk/react-base-table#185]
This is a sample [code](https://codesandbox.io/s/jolly-satoshi-tqikl?file=/src/Base.js:1345-1356).

Everything works fine since I can get the data of the selected checkbox but I've found out an issue regarding render update.
To reproduce my scenario:
1. Check Select All
2. Unselect a single row
3. Uncheck Select All

UI will only update after a scroll event.

Thanks in advance.

**Comment by nihgwu** [comment]
be sure to change the reference of the array when you want a re-render, line 96 of Base.js
