### ISSUE TITLE
Unable to Render when using AutoResizer in Enzyme Test File

### ISSUE THREAD

**Issue by ajbee07** [Autodesk/react-base-table#189]
This is my sample [code](https://codesandbox.io/s/icy-cookies-1xspk?file=/src/App.js).

My problem is whenever I declare `Table` inside `AutoResizer`, the whole Table will never be render.

```
 <AutoResizer>
        {({ width, height }) => (
          <Table
            data={Data}
            width={width || 280}
            height={height || 420}
            rowKey="Name"
          >
            {Columns.map(({ dataKey, ...restProps }) => {
              return <Column key={dataKey} dataKey={dataKey} {...restProps} />;
            })}
          </Table>
        )}
      </AutoResizer>
```

But if I remove the `AutoResizer` my test will pass.

```

<Table
     data={Data}
     width={280}
     height={ 420}
     rowKey="Name"
>
    {Columns.map(({ dataKey, ...restProps }) => {
         return <Column key={dataKey} dataKey={dataKey} {...restProps} />;
     })}
</Table>
```

My test:

```
it("should render BaseTable", () => {
  expect(wrapper.text().includes("Durant")).toBeTruthy();

  //but if I remove the Autoresizer then the test will pass
});
```

Is there any workaround here? 
Thank you so much.

**Comment by nihgwu** [comment]
You should mock the `AutoResizer` to something like `({ children }) => children({ width: 1000, height: 400 })`

**Comment by ajbee07** [comment]
Do you mean I need to separate the baseTable with Autoresizer? and only test the component with baseTable?

**Comment by nihgwu** [comment]
no, mock the `AutoResizer` component in your test or setup, like `jest.mock('react-base-table/lib/AutoResizer')`
