### ISSUE TITLE
A way to make scrolling smooth with a lot of columns?

### ISSUE THREAD

**Issue by apieceofbart** [Autodesk/react-base-table#197]
Hi,

first of all thank you for working on react-base-table, it looks really great and is well documented!
One of the issues I have is that when working with a large number of columns scrolling becomes janky. 
You can see it here: https://codesandbox.io/s/react-base-table-0s214?file=/src/App.tsx

I understand there's no column virtualization at the moment but maybe there are some workarounds I could try?

**Comment by nihgwu** [comment]
dup of #36 but I'd say it won't be supported in the near future, maybe you could use a custom `rowRenderer` according to the `scrollLeft`
