### ISSUE TITLE
表头分组，并且支持fixed和拖动配置有什么好的方案吗

### ISSUE THREAD

**Issue by 52flutter** [Autodesk/react-base-table#198]
按照多表头的方案尝试了下，拖动用不了，如果设置fixed的话表头和内容会对不齐

**Comment by nihgwu** [comment]
Sorry I don't quite understand what's your problem here, a screenshot or gif would be better

**Comment by YinRenjie1993** [comment]
大佬来个表头分组的demo吧

**Comment by nihgwu** [comment]
https://autodesk.github.io/react-base-table/examples/multi-header this example won't help?

**Comment by YinRenjie1993** [comment]
![image](https://user-images.githubusercontent.com/11569655/88494556-29923a00-cfe9-11ea-886b-d25e8eb5eb20.png)

**Comment by YinRenjie1993** [comment]
类似这样的 分组显示  和多表头有点区别吧

**Comment by nihgwu** [comment]
https://autodesk.github.io/react-base-table/examples/draggable-rows-frozen

**Comment by YinRenjie1993** [comment]
我的意思是表头分组，我这样实现了以后 ，调整列大小用不了了，设置fixed={false}后 表头和表内容会对不齐

**Comment by nihgwu** [comment]
哦，终于明白了，因为merged cell width是直接根据`style.width`来的，对于`fixed={false}`的情况，width其实并不是真实的宽度，因为是flex布局，是个好问题，之前从来没考虑过这种情况，我们内部是必须`fixed={true}`的时候才能用column groups，`fixed && columnGroups && !Array.isArray(headerHeight) && !headerRenderer && headerGroupHeight;`

**Comment by YinRenjie1993** [comment]
这种场景能不能底层地址下 因为有的表格字段可能很少 铺不满  不设置 fixed={false}的话 后面会留白很多

**Comment by nihgwu** [comment]
感觉想不到比较好的解决办法，因为在flex布局下，每个cell的宽度都是自动计算的，里面还涉及flexGrow/flexShrink/flexBasis的情况，唯一能想到的方法就是去取渲染后每个cell的真实宽度，然后再render group cell，这里就必须用`flex: 0 0 width`了，不过还是感觉有点复杂

**Comment by 52flutter** [comment]
老哥啊  多表头和表头分组能不能搞下去  现在的这种表头分组有点麻烦 而且不能支持子属性的拖动

**Comment by qiang-chen** [comment]
大佬 这种合并行怎么做的
