### ISSUE TITLE
Frozen columns can have incorrect height on initial render when using dynamic row heights

### ISSUE THREAD

**Issue by jamesonhill** [Autodesk/react-base-table#199]
Frozen columns height are incorrect until the first grid re-render.

Example: https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDACsrdtBgAzAiABeeUVF6Zc+YqW1FxlSRBl0ZAclUa8AWjUB3B9dZtwS5QEsAHjicFFRomBLUAHTIRAAONKYhMuFgAJJgnDh+TBgAfDAA3iwwMPA4sHaaYEUwPsowCZJpGX4wADwwdNkVeHzBkhEAYmqVwj4EOMBQPuARADIAogMAKtW19clNmTB5ABxdwz2YfaiDB2Cj45PTYBEASikA4gASK8XjUIgEYAUwEX-JMm63wAvixgR5FLBMjEiOljmAANI4ACefGsyQcDGsLBYAHpcTAiJxODAICBkDhSYgAEY1UjICAsZQgAj1UqwHx8BgAbhqbQ6DB5NQA1MLsoVitwdBEYogIAALGgS4q-P5SogAbQYAF0pNVij5OAAuGAAAwAJPl1VrtRFDcCHBAaQ5LT5gaa9SqYDDxmAoCljTBrTq7ZxPSqNdDYUEzKgkcjtSbTQBlGkwV3u8Pg6rqmVyxXK4p-CLWgBMuv1NUDFqtPA15dDDqd1Jd+TdHsrPrw-sDZdthvDxUjfhhcNjiJRibNqdpGY7xWzkp4eYVSsrxb7g6rSctfcbjudzdb7a3Xb9AZ3tZ09f7nCbzrnW+Ho5jIXjU5Tzpn6bbmeq2dBTwOBgKBxhEHg+EQMBlHgEhSDAGh1Q8aEWS4HBlCIRB4FgGhsnQPIaGqVoliIalSkrXwAk4StkggdB8kowJ4QgUEvXVejQJwcCdFYlUgWMej+J4XjiijMc3xReixNfSR4xEmAcGgHxolIThbhAZwnhwHwsHlKB6IAFgYXjcRyFhWCAA

When the above grid loads, you can see the grid border/box-shadow below the last row. Once you hover over any row or trigger a re-render in some other way, the columns re-size correctly.
Working on figuring out a fix.

**Comment by jamesonhill** [comment]
Actually, I think this may happen every time. It's only noticeable when the total rows height is less than the grid height.

**Comment by nihgwu** [comment]
Thank you for the reproduce demo, I will dig into it soon

**Comment by jamesonhill** [comment]
Thx for the quick fix.

**Comment by v1690117** [comment]
Thanks for the fast reaction!  This fix helped me a lot.

**Comment by jamesonhill** [comment]
@nihgwu This is still reproducible unfortunately. See example here: https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBA5gUzAgTgQyggwiANgVwFtIAmGAXhgApR8xZKBGABgBoYAHFBAMwEsAHhRgByUAWIBaEey4gOEAJQUAfACgYMZAHcYAQRToAnjRB0oigHT9cuKsyuE0HKqYlh24omACSYACYIAsrkKtQA3hqaMJaxcgqsUZoA1ghGAFwwAAYAJOFcvIIAvnlexH6BAkVZidEw-hhoANJpmbn53PxVpXjeFUHVtdFQfFC4CG047jA97v1VNUkw2nz+UAAWmYwArGxRRYqKaqCQsIjI6JgAIo1klG7eEJ5m9MIkzGycnYLCIigg2mkIXUmh0+kMaBMtHoVhsdgclicLio-207FR82BMEidW4UHwKDAMDKkEs3H8+GACCoS00KIBNygaGe7hZfQCQSxOLq0RO0GJCFsADU0AQEMIsgAlAEzcIYjlVGCSGBTWUk+ZFGDS3R5eWVTXK1Wzdn6rUy3UAjVKlV4NW9coKzXa2V6gbWo3hdWOrK06KoxloADaJMsDSZLSMAF1hFThaL8AhfZo8QSif7Gr6ikM6tyeTBVm08gUuiU5ZbvdmeRw0Nx6D5-JkwPhbJXNEUlkc252YMdwPySRBhOdUBhsPbSFQWEc+bAw2gh0gR9dbg9iE8YABmI4Aem3M5gPH+AC8kAGFxdRwHV5B2Ix2CJDyAT2BJKigWpe6cD4IEP4po8Y3HCBEWcVwSTZB1Ki5KJxlgR9nyiPgeGoL1KhgAAeGBGGUeCkGEf9iEsAAxY9Tz4bhgBGcBLAAGQAUSIgAVRDkOveYYDCAAOHDSKJSgCLAYjeKuciEEovhqMlHwAHEAAlmOTBB8UJbEYlicCD14mB2wOD99yCasAgEiNfhJSRmBED9dxgNB-H8GAIBAQhxQgfAACN80wQgIDUbcACoDxAFBqFg-NhGYABuMLMJYSL8wAani5RuTnSwOHwCB1ioXM1NDRpA2YSNKwLbI8jnArI0sVYikkVy3MkPI+EGJZq1rKB60ycrCqq-whl0zRUvSzLsqWWI8qZQMSCKpYSvacqpp6mq6oa8ImsWOpWqQdqG3qfKFtWStAwMtAjPHCNIzaABldzZTWvru0GjKspysb5umupZrKvbKuq2r3L++rGuajaay2jrSvCN7FoBla7qWI6BEMv8zrSC7smu+qMdu4HtKOTU-O3PS+1gKBuAQM9KDoHhcAwTAwCoOcjjUAygtnXg0GbWAqCxGlNHQxi0Dc8Yli6X8lgHchwlF5H3Agds6jnSXSYQcnGnl6JjtO9wI0lzWZe8CN1c0BBoD4JxMH8bVZIQPg4HWKBJYANmYdXt3UI4gA

**Comment by nihgwu** [comment]
@jamesonhill Sorry for the problem, I enforced to always show scrollbar on Mac, so there will always a re-render on mount, so it's enough to force update only in cDU, but apparently there's not enough, if the scrollbar's width is always 0 there won't be another re-render

**Comment by jamesonhill** [comment]
I see what you mean. If I force scrollbars to display it does appear to size correctly.

**Comment by jamesonhill** [comment]
Can we modify `forceUpdateTable` to also call `this.forceUpdate()` ? This seems to fix it for me locally:
```
forceUpdateTable() {
    this.table && this.table.forceUpdateTable();
    this.leftTable && this.leftTable.forceUpdateTable();
    this.rightTable && this.rightTable.forceUpdateTable();
   // add the below line
    this.forceUpdate();
  }
```

**Comment by jamesonhill** [comment]
As a temporary fix in our codebase I added `getScrollbarSize={() => 0.01}`, which force fires the cDU check.

**Comment by nihgwu** [comment]
sorry I have a busy day, will try to fix it soon

**Comment by jamesonhill** [comment]
No worries. Just figured I would share w/ anyone else interested how we're working around it.

**Comment by nihgwu** [comment]
a new version 1.10.7 has been published, this time I went with the other option I mentioned in the previous fix
