### ISSUE TITLE
Frozen columns are not rendered with dynamic row height

### ISSUE THREAD

**Issue by RedFish** [Autodesk/react-base-table#206]
When I add an item to the end of my table, the frozen part is not rendered directly, it refresh if I add another item or if i move the mouse over the table.

Here is a codesandbox to reproduce: https://codesandbox.io/s/react-base-table-dynamic-row-height-qg16s?file=/src/App.js

I have seen similar table from the example (https://autodesk.github.io/react-base-table/examples/dynamic-row-heights) without this bug, what am I doing wrong?

**Comment by nihgwu** [comment]
there is a bug before when data won't fill the whole table, it has been fixed in the latest version 1.10.7
