### ISSUE TITLE
Inconsistent scroll position behavior when column.frozen changes

### ISSUE THREAD

**Issue by jamesonhill** [Autodesk/react-base-table#207]
If a column is dynamically frozen, the scroll position of the grid is reset to the top. However when a column is dynamically un-frozen, the scroll position of the grid does not change. Is this intentional behavior or a bug? Below is an example. If you scroll down then click "set as frozen" to freeze the first column, then scroll down again and click "set as un-frozen" you can repro the behavior. https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBAJgQygg4gUzGgTkkWYC8MAFAJSEB8JA3gFAwwCWcAXDAGYIDW2AdDmDggAtrwCuY5mQA09GGATC0bTjyy8ANnjSiA7njgQZcgOYY42Fdz4ChogEYgQGtAjBkYAfhgByYQhcfGDYfdh0AtB9ZBghQLGUYOgYGfygACys1fjc7XjAxYXtsYgB2AAZyAGoYAGYy6JgAXwb7Rix0xABPTL5EKDReIqhdNAxiAEYATkmAVmkYACYyspnSBqRkYDSlMCgIHvVbETyCoqxiVYaLWKxGAAcoRnADzW1RCAx+sGA0YwZwxgaF6MXbYTBQXgAjR-GCgMS7LDdDjWdQIOBweIQCC8OEIzowtEYtBYthJZLQeJoKAvQmY7EU0ZQACC6LpMIYwEYUCRqj4tOJ2M53PZMAAXvcAMIgCw01kC3jiu5Siww5q0RqkWi0UCQWDoQTYKW7BAg7CEGDQTouOC8OCMABuAAM5PYEMAuCYsCB4XAALSgLRYNgAEmody9dwglDkDHDIEjvDMBvwBFTvn8gS8vg0jBMaSg9g0YkiwV8dxBXB8jQA3HIA3g2Lo0ly0LWGI4sBYsL6cHaxPtancAB5tmC6ZjpNhLYejtJoXP5qdlGdydjgKC+iCMUUJcYANhXDDXu19IwX1Jgjg0cFHOcwvrn56Xh5g-SHG4CubAbB+oKwtedbVwGgGB9S7c1iGoGAk3AjVKBIOQAB4wMNdcTUwfAYOwAhqCwrBGgoGNEjwwg0z8CIgm8HxACEyIIQkAATIqyQgB6FCsCNZBTSwQjNSA3UYAAZTiNBzUta1eAgO43GdDlnAbGBQzjSN4OIJT6WEmAKCIPcyizHxPVGMA6N8eI4B8Uga1oQCdRApkoE2bZPlE7lxLtJ0XTdD0vR9f05KDGAczzKBPQQTpR3HOBJ0WZcRzkR8gufWKGDvNAH3nBLopfN8P0C79YU+bBRw7LsezRRh+zYAAWF9638kKwqsrUbNgCxODEDQoAAESQBBzUwXQYCZLAcHxcZlk1BheHYQFoQqOReH8O5iD6VAMGwXAsAmmAJLwKBiGIBB5nscgCCoA68kUESqHsC6lCzcZS19cZSF45r4DQNqOoE3bzSgngkR8BQlCiGADEsQTdoAeU7PgmQEiUmi1NAhzuH7WoQdrYGADQECxQa7juGBka+QwYAAJVcYAISlYRUcwXZEjrYCoCwMQqbwVSIwgcgyRiMQ7mKNTSFHBh0kYelkH6X6iIYFa2HRzHuuQBpkgtXaACEkQVr7dpV5IoBAZANAACXSxcYHqGXYWcApIDYABtK2GF51Xkn+kIgciPXXdfLkXBCAA5S6oid5IVoAaTQAHPZDn3VYiqLxhmS24+STFtwQQsEhZ4tvddiBdsz-3X1ZtA84YNVU5dn33d8WJtFj1PfagYufCEhvy7DnrI4B+v4gWpA0kb1OE4yGAdM7hhPxMPKpSLYQwF4Jlcp2amAFEA4AFTXsnJ7V9oi4STgNA+TvK7j6vXdr-TzGwYe48eFuEhoxi94jqOQjw++fZ+DQNAp5M4NIL5T-krBAbASJwVOjAZCt9MJwJwnhRoMBmIUD3qPNgE9Q5T1ymwOetsl4r0+LwCUG9t672wfvZAWc2A5zLqHc+PtL6q2vq0doaQujf1do-Vu6s2gdFClw1W78AZsIEZ0IRXdkDoHskAqCAZbbzC9LoMBTQTqESbmnEAKier2wUQvW03co4AF1eAGwADIgGABEJWaABIsxBCYEUPsMEwDGinJu09Z42wMcvL8q9eBkwAJIoGNpvPeBcD40JLrnBhndmFuw-r4DYbpHK7AgJI0Wftn52QcqvDJb8jEAxSVsfJmSxwTjHlgzRXi8E+MXn4meATSFbx3nvOcaJsAAK7EA9RMDcmpNXhQTwiFmIDNKZ8NBlDf7-zgXIkBGhVFQKoIhcZaSoAUGoDMsBjRRlrKGWfeJlDr7XGALcB4TwjJ7x4c-TqxIzn3EeOAcpIiQinPOU8q5lDXFLA8andOopD60NLhEwu0S6GHNDgkhg18oTlJuSENe-hAQvKKSEOF6DKlLj+XHAFQKYn0M0ZE6hxcIVxKhccpJPhcQswkdc7JIQpTwlpai5APcQg0sROU1x7i954vBSCyhxL8VktTow120KYDX35FieFDLfAsiJLKwpbKqUyolpSKA3KsXRRxT7flpLBViqOZo6VVNLnasimPXllDakwHwb4ohuwSFkLaZQ9gXodzePnovAAYp6jAnU2hoHNeAQJISwl7xmd07A8zlFLL6cQShDBEL2DEPZcAybkjgAlDmd0OEPDQMlT7MW9IqT2KQL8Ytcc5avmbBLSthjkBTUBP0c4Q54JDl4MwGAABCNM8aerdrgGsLNqsNRjqaI0LNGjNHJApsIEA9o0BZtGWmjNYBZ2p1Hcaq2xiiLTtVqWsxhsAim3POaMoo5p1yBzfU767RRIa06PBF2b0wYpioZrXgH7SJEAfVAaGXYl7w3uo9cYRE3orXNPbXgcHj3QEbStfdwih3Ev2odS8iaED22Jd+-6xjNKXlw8+3gBGsy-rYL6D9L0iIIfLZLKtVs8OdDzitPWE6K5ahiFSCm7AILxHYH0l2x7BPmkE9e7jMB4jJg8G+5miR4A9XmCxpo5oEOMaIowfjxBRMfR5lbN68V8zqfrfwD6iYqSb1Pf-bREBz1BTICLfWZmDZGwcyZogxmoDOcPWnKkYgsBgAQj7RCW7XapvTQbMAlCc15q4AW4TWb6NQArf0SCk6DYmBMMXXtGnG1ZZy4SudnGm6ND8z7cLPtrPZZcNbH1EBQ5rqi+AKryRIsbtBmAXNjB83UELVQSVb1+pzyjEQfL-QcT1OxItfaQ55iMETVBODvB5scADXlRgf6LZZgdX6jbQb4ihsXuYtevrN6lj27wf1IAvWHZDZ83gAdIYBzXmo4WlCUtparfV22A4RvOCjBqZz46CKUIElSGAuN1u3YwE15i67ottZTYj8AXWet9YG4zTRw20C6FG6Z8WElGNTYawPJaxA1uLZUstuDa2PWw+9QQm7d3g3Haey9t7GoPuaK+4x4B+i7byDxwT4HDCweaIh7AaH8JfQM69fD1Hm6mtK9i91+LiXX3JbMx8VL-Pq2yx6g7Fa+p1oG3OGsbacHkN7wrltMVFXXbI+SIqpg-RhCvhAJ7u4iuWvK9TohTeh93WMCHGgOAQq0AuCpsHnH02cJZt7XlnXJPCt1e8BNgYgv6R5t+PUGAlVyC0JT427PlDHc+2JI8VI4eybaI81AHClUygV9ditHCK1W+qxYzhFjXfs3dfvbtHCx670+oA-3hggmR8694x9fvqCrajPC1tadjQgA

**Comment by nihgwu** [comment]
it's a regression from the dynamic row height feature

**Comment by nihgwu** [comment]
Thank you so much for your wonderful repro demo, this is a long existing bug, we didn't discover this issue internally because we always have a selection column frozen to the left, working on a fix
