### ISSUE TITLE
Confusing of using rowProps vs rowRenderer for row redering

### ISSUE THREAD

**Issue by dohoangtung** [Autodesk/react-base-table#210]
Can you explain a bit about the purpose of using the tagName in rowProps,  I'm a little bit confuse of using  rowProps vs rowRenderer.

As in the code example of Draggable Row, we have rowProps defined as bellow:
 const rowProps = args => {
          // don't forget to passing the incoming rowProps
             const extraProps = callOrReturn(props.rowProps)
        return {
            ...extraProps,
            tagName: Row,
            index: args.rowIndex,
        }
    }

above code, table row will be overwritten by Row (using rowProps), but beside we also have rowRenderer for overwrite the render of table rows, so if I want to customize the row render, which one is correct?

**Comment by nihgwu** [comment]
that's a good question, `BaseTable` will wrap the cells in a internal defined div, `rowRenderer` can only change the `cells` part but not the wrapper itself, so it's actually a `cellsRenderer`, the `tagName` provides the possibility to change the internal wrapper 

so if you want to change the cells you should `rowRenderer`, but if you want to change the behavior of the row, like attaching testId to the row, you should use `rowProps`
