### ISSUE TITLE
Input cursor disappear when use resizable table

### ISSUE THREAD

**Issue by Sharon519** [Autodesk/react-base-table#211]
I want to type in input box to request other data to render resizable table.
But input cursor will disappear and I need click the input twice to continue type, though the input is still the activeElement.
If I config the resizable prop as false, the cursor won't disappear. Any idea?
test example:
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDBa3bQYAMwIgAXnlFRemXPmKldRcZUkQZdGQHJ1WvAFoNAdye3WbcCtUBLAA8cTgoqNEwJagA6ZCIABxpzMJlIsABJME4cAKYMAD4YAG8WGBh4HFgHbTASmD9VGCTJDKyAmAAeGDpcqrw+UMkogDENauE-AhxgKD9wKIAZAFEhgBVa+sbUluyYAoAOHtG+zAHUYaOwccnp2bAogCU0gHEACTXSyahEAjAimCiAakZL0wDJJhA-JoiAAjcoALhgUAIiBwAF8WKivMpYNk4kRMqcwABpHAATz4tlSTgYthYLAA9PSYEROJwYBAQMgcOzENC6qRkBAWKoQARGuVYH4+AwANx1DpdBRyvwAahVuWKpW4eiicUQEAAFjRNaV-gDtUQANoMAC6UlqpT8nARAAMACSFC3Wm1RJ2opwQXlOD1+VEu+2mmB4yZgKBpZ0wL2232cCOmy24-EhCyoEmkm2ugDKvJgIbDacxtQtuv1RpNpQBUS9sjtDrqCfdnp4lpbKf9gehwcKofDbejeDjCebPqdadKGYCeIJOeJZILMBdxb5ZdHpUrWp4NcNxrbjenc-bro9077AaDA6HI4v49j8avXb0PZnnH7QZ3F4XJdszCPN103IMt1LYdy1qSt0W8DhEUmEQeD4RAwFUeASFIMAaAtLxcVFLgcFUIhEHgWAaFydAChNbEYEtfwKMIYJTBkCAKiGPxmMmThTBtPh7hwIhpiifUcELPRSBoJEcBQvRWFKejLT8CB5hAFk-DALB2IqNI1I0zgtKwATMCEkSoDEjjJKEGhSPgDjFJgWp6KY0gCFMPgaBwAA3CdqNott6NIAJYEwXyJyiPQCFwSyfKIJAcCCnxYHBciwqQuTTCiNzCBoPwBXyfkcGQS1KRXJw6FsGdMmyAB5VQZOyKBcgKSqnNKNsOLjAzNO0mTkRwDr2QqFY-C5EBECgRIAqKNtSm6-T1L6rA7ISxz5pGqAuJ41ixDSijhtRGR5EUWDalqT5vl+Gg23aIyfLyTb2i0vVYHAMgDXxXB0EKXKPJ4VEYHpJ7I1KeswdU5ajO0zbSgAfg6B68mh4zG3aelkbhmAEXaFYYXKbHSn8IJOCJuAVwgX6SeCQkIHRMGwYtanuPcva9AZxnTRBUxqYuUxOa5mBM2XECyV+kXgMkPNBa5kHnMZ2WMax0pWHRIA

**Comment by nihgwu** [comment]
related to https://github.com/STRML/react-draggable/issues/315, I'll sync the fix soon
