### ISSUE TITLE
Collapse node when dragging

### ISSUE THREAD

**Issue by dohoangtung** [Autodesk/react-base-table#215]
Hi,

I'm facing a problem with basetable and sortablehoc. The datasource of basetable is a tree. When dragging the parrent node, I want the node to be collapsed (hide all children), and as basetable be rerendered whenever it is expanded/collapsed lead to the dragging state is lost. Could you please suggest on how to overcome this issue?

Thanks,

**Comment by nihgwu** [comment]
maybe you can only enable drag&drop while the node is collapsed?

**Comment by dohoangtung** [comment]
I think, the better solution could be adding css classes to make children invisible (display :none) when mousedown on draghandle. But then, how can I force table to adjust height to get rid of the white space:
![image](https://user-images.githubusercontent.com/40049759/90420411-210dba80-e0e2-11ea-8838-18457315a026.png)

**Comment by nihgwu** [comment]
@dohoangtung I don't think that's a good solution, the expanded children nodes are not nested in the parent node, but are siblings to the parent node for(if not doing this if there is thousand children nodes, that will make virtualization takes no effect), so when your dragging the parent node, only the parent node is the active node, without the children nodes, so I still suggest disable d&d when node is expanded
