### ISSUE TITLE
Column Hidden props

### ISSUE THREAD

**Issue by dohoangtung** [Autodesk/react-base-table#223]
When set props hidden to columns then table layout will be issue

![image](https://user-images.githubusercontent.com/40049759/91381744-4de46f00-e852-11ea-9c8b-b1d1959c8b1e.png)

**Comment by nihgwu** [comment]
could you provide a re-produce demo here https://autodesk.github.io/react-base-table/playground?

**Comment by dohoangtung** [comment]
Sorry, my fault. I've managed to fix it by myself. I use custom row render while not handle the column hidden correctly. But I think the core logic should handle this also as column hidden is a global configuration, my thought.

**Comment by nihgwu** [comment]
the hidden columns should already be omitted from `columns` in the renderer function
