### ISSUE TITLE
文档连接打不开

### ISSUE THREAD

**Issue by coingpaic** [Autodesk/react-base-table#224]
文档连接怎么打不开了了？https://autodesk.github.io/react-base-table/   拒绝了我们的连接请求
帮忙看下。谢谢！

**Comment by nihgwu** [comment]
I can open it without problem

**Comment by coingpaic** [comment]
真的无法访问噢

**Comment by nihgwu** [comment]
那你应该检查一下你自己的网络。。。看看其他的github pages能不能正常打开
