### ISSUE TITLE
Help Wanted: Custom Renderer with React Hooks

### ISSUE THREAD

**Issue by ashishsantikari** [Autodesk/react-base-table#228]
Hello,

I did not understand the explanation on [https://autodesk.github.io/react-base-table/docs/get-started](https://autodesk.github.io/react-base-table/docs/get-started) in the **closure problem in custom renderers** section.

Could you please explain what needs to be done to fix the issue. I am stuck with it for few days now and not able to resolve the re-rendering problem. An example using **useCallback/useMemo** would also be great way to understand the problem and the fix behind it.

**Comment by nihgwu** [comment]
won't `ignoreFunctionInColumnCompare=false` help with hooks?
if you have set `ignoreFunctionInColumnCompare=false` but still want the optimization, you can memoize the renderer via `useCallback` or memoize the columns via `useMemo`

**Comment by ashishsantikari** [comment]
Yeah, finally understood the fix. :)
