### ISSUE TITLE
Expanding Column is not working

### ISSUE THREAD

**Issue by ajbee07** [Autodesk/react-base-table#234]
I'm trying to create expand function for the column but I can't figure out what's wrong with my implementation.

Here is my code so far : [codesandbox](https://codesandbox.io/s/youthful-gates-ir0qm?file=/src/Base.js)

The weird thing is that if I click the index 0 dropdown then all of the remaining rows will also be expanded.

Thank you in advance.

**Comment by ajbee07** [comment]
So After playing with the code it seems that I need to replace `index` with `id` as the `key` of `Table`.

Is there a way to change the `key` to `index` ? but yea it's not a big issue

**Comment by nihgwu** [comment]
rowKey='index'
