### ISSUE TITLE
Dynamic Row Width feature

### ISSUE THREAD

**Issue by SergeyVolynkin** [Autodesk/react-base-table#235]
Greetings, `react-base-table` already implements [Dynamic Row Height](https://autodesk.github.io/react-base-table/examples/dynamic-row-heights) feature – and this is great.

Do you have plans to add `Dynamic Row Width` that can be configured per column in the future?

**Use case:**
- We have 5 col. table that handles thousands of rows, `Column 3` renders formatted JSON. We don't know JSON text width, so we need to calc it on the fly (at the time of render, the windowing is enabled for rows). `Dynamic Row Height` helps us with proper row height, but there is no support for auto width.

**Open questions:**
- How would you recommend implementing `Dynamic Row Width` for 1 or several columns in the `react-base-table`? (when it's done, I'm also interested in opening a PR for the `Dynamic Row Width` back to `react-base-table` in my spare time)

**Comment by SergeyVolynkin** [comment]
@nihgwu I'll appreciate your feedback

**Comment by SergeyVolynkin** [comment]
cc @jamesonhill as the author of `Dynamic Row Height` https://github.com/Autodesk/react-base-table/pull/170

**Comment by nihgwu** [comment]
do you need horizontal scroll? if not you can set `fixed=false`(which is default) and set the columns with `flexGow=1` to occupy the available space
or you can use `resizable=true` to resize the column to a proper width, I don't think auto column width is viable as with virtualization, we just render a small sub of items, of we can't know the max width for a column, also dynamic row height need a defined width to work, correct me if I'm wrong

**Comment by SergeyVolynkin** [comment]
>do you need horizontal scroll? if not you can set fixed=false(which is default) and set the columns with flexGow=1 to occupy the available space

Yes, my table can have multiple rows that can overflow the container, so the container will be scrolled to view the rows.

--
For now, in my table, I have a plan to just sample the text data (first 100, for example) to guess for the width + enable user resized columns 

--

> I don't think auto column width is viable as with virtualization, we just render a small sub of items, of we can't know the max width for a column

I was thinking about "jumpy" column width scenario, where we render only 20 rows, for example, and the current width of the column will be set to the max from that 20 rows -> and then recalculated on the scroll.

**Comment by nihgwu** [comment]
I'm afraid changing column width on scolling won't be a part of BaseTable, I think it's a bit weird, if you scrolled and get a larger width, when you scroll back, will you narrow the width or still keep the max width
I think you can use a custom cell renderer to measure the size of the cell on rendering and update the column width dynamicly, it's achieveable from user land

**Comment by jamesonhill** [comment]
I've thought about this, but hadn't come up w/ a solution to add internal support for both dynamic width & height since each relies on the other. In most cases using `fixed={false}` and `flexGrow/flexShrink` works like @nihgwu mentioned. But in some cases I do need a dynamic width for a particular column but fixed/resizable for others so that doesn't work. One approach I take in our internal repo to sort of achieve this is to sum each of the non-dynamic column widths and subtract it from the container width and applying the difference to the column requiring dynamic width. Similar to this:
```
const colWidths = useMemo(() => {
  if (!columns) return {};
  let totalWidth = 0;
  const widths = {};

 columns.forEach((col, index) => {
    if (index !== whateverDynamicColumnIndex) {
       widths[col.key] = col.width;
      totalWidth += col.width;
    } else {
        widths[col.key] = containerWidth - totalWidth;
      }
  });

  return widths;
}, [columns, containerWidth]);
```
Hope that helps.

**Comment by SergeyVolynkin** [comment]
>I'm afraid changing column width on scolling won't be a part of BaseTable

Makes sense to me as well

>I think you can use a custom cell renderer to measure the size of the cell on rendering and update the column width dynamicly, it's achieveable from user land

Thanks for the tip, I'll figure that out : )

**Comment by SergeyVolynkin** [comment]
@jamesonhill Thanks for sharing a snippet!

**Comment by nihgwu** [comment]
looks like your tables are much more complex then we have internally xD
