### ISSUE TITLE
Override the code that renders rowClassName

### ISSUE THREAD

**Issue by faassen** [Autodesk/react-base-table#236]
I am integrating react-base-table (thank you!) with MobX. MobX will automatically rerender observer React components when any of the dependent data (which is automatically determined) changes.

To this end I've defined a custom `cellRenderer` that returns a mobx observer React component. This makes cells responsive to MobX changes.

react-base-table allows a function to be passed into `rowClassName`. I want this function (or something like it) to be responsive to changes in the underlying data (adding a className to the row if certain conditions are met) it uses (rowData). But because react-base-table has no idea it should rerender a row when `rowClassName` changes it behavior, this won't work out of the box.

I've tried to make it work by using the `rowRenderer` prop, and this *almost* works - I can use an observer React component here, and now row rendering responds to changes (not `rowClassName`, but my own function, but the principle is the same).

Example:

```ts
@observer
class RowRenderer extends React.Component<{
  recordClassName: (record: any) => string;
  cells: any[];
  rowData: any;
}> {
  render() {
    const { cells, rowData, recordClassName } = this.props;
    const className = recordClassName(rowData);
    return <div className={className}>{cells}</div>;
  }
}
```

MobX is smart enough to know that when a observed dependency of `recordClassName` changes, it should rerender this component.

But my custom RowRenderer has to introduce a new `div` to introduce the class, and this screws up the styling. 

What I'd *really* like to be able to do is to wrap a React component that renders a row with my own component, introduce a new className based on observable state, and tell react-base-table to use that. `rowRenderer` executes too late for me to be able to do this.

So something like along these lines:

```js
import {TableRow} from "react-base-table";
import {observer} from "mobx-react";

@observer
class MyTableRow extends React.Component {
    render() {
        const {recordClassName, className, rowData, ...props} = this.props;
        // add in our own class name, based on observed data
        const amendedClassNames = classnames(className, recordClassName(rowData));
        // reuse the original TableRow
        return <TableRow className={amendedClassName} rowData={rowData} {...props} />
    }
}
```

And then use it somewhat like this:

```js
      <BaseTable
         customTableRow={props => <MyTableRow recordClassName={getClassNameForRecord} {...props} />}
         {...props}
      />
```

I'm not tied to this particular implementation strategy. I just am looking for a way to make row class names depend on observable data, and in general try to make react-base-table work well with MobX.

**Comment by nihgwu** [comment]
I think you can use `rowProps.tagName` to inject the custom Row component https://autodesk.github.io/react-base-table/examples/extra-props

**Comment by faassen** [comment]
Thank you very much, I got it working! 

I don't see "tagName" as one of the props you can override anywhere in the API docs, perhaps I missed it? I should have traced where 'Tag' came from when I was reading the code.

**Comment by nihgwu** [comment]
Yes, it's not documented, this is the most powerful api but should be the last option
