### ISSUE TITLE
rowRenderer add option to render using default behavior

### ISSUE THREAD

**Issue by smblee** [Autodesk/react-base-table#237]
Hello,

I have a use case of doing the following:

```
CUSTOM Sticky Row (no columns)
Regular Row
Regular Row
Regular Row
Regular Row
CUSTOM Sticky Row (no columns)
Regular Row
Regular Row
Regular Row
Regular Row
...
```

An example table with some data:
```
**PEOPLE THAT START WITH "A"**
Abby McDonald | 123 | Jul 29, 2020 ...
Abe Lincoln | 123 | Jul 29, 2020 ...
**PEOPLE THAT START WITH "B"**
Babe Ruth | 234 | Jan 13, 2020...
...
```

I am not able to find an easy way to achieve this. I took a look at "sticky rows" but I want to achieve that with a custom row style without any cells (https://autodesk.github.io/react-base-table/examples/sticky-rows).

I think the only option I have is using `rowRenderer`, but I dont want to customize ALL row renders, but just the sticky custom ones.
It would be nice for the rowRenderer function to expose a function like `defaultRenderer` so I can do something like...

```javascript
rowRenderer = ({ rowData, defaultRenderer, ...rest }) => {
  return rowData.isCustomRow ? <div>People that start with {rowData.startWithLetter}</div> : defaultRenderer
}
```

(although doing it this way forces me to pass in a customized array of Row[] with type `PeopleData | CustomRowData`)

What are some suggestions here to achieve this?

**Comment by nihgwu** [comment]
the default renderer is `cells` in the params, here is an example https://autodesk.github.io/react-base-table/examples/detail-view

**Comment by smblee** [comment]
Great! Thanks @nihgwu :)
