### ISSUE TITLE
Image is re-rendering when scrolling  

### ISSUE THREAD

**Issue by ajbee07** [Autodesk/react-base-table#238]
I have a component that has an `image`

`   <object type="image/svg+xml" data={`${url}`/>`
                
but the problem is if I scroll, it creates a flicker effect because the component is re-rendering even the component is still visible within the scroll area.

Is this the expected behavior? or there's a workaround to prevent re-render of the component?

Note: The re-render is only visible in the `<image>` itself

Additional Info: I'm rendering the component inside an `expandedRow`

**Comment by nihgwu** [comment]
could you share a reproducible demo, generally the cells should not be re-rendered if nothing changed, and the browser should cache the images, I don't understand why there would be flicker effects

**Comment by ajbee07** [comment]
I solved it after changing the svg content `xlink:href="data:img/png;base64` into `xlink:href="data:image/png;base64` to use `<img>` tag instead of `<object>`
