### ISSUE TITLE
Support for frozen footer?

### ISSUE THREAD

**Issue by danielwyb** [Autodesk/react-base-table#239]
Hi,
really nice table! Curious if there is an option to add frozen rows at the bottom of the table?

Thanks!

**Comment by nihgwu** [comment]
no, the only way is using `footerRenderer` to simulate that

**Comment by danielwyb** [comment]
Okay, thanks. What's the best way to keep the content at the bottom in sync with the remaining horizontal columns?

**Comment by nihgwu** [comment]
no, listen to `onScroll` and sync like this https://github.com/Autodesk/react-base-table/blob/master/src/GridTable.js#L51

**Comment by danielwyb** [comment]
Perfect, thanks.
