### ISSUE TITLE
AutoResize complains about unset width

### ISSUE THREAD

**Issue by jonquark** [Autodesk/react-base-table#242]
It seems to work in the playground:
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDBaxYscADwAOIAlxwAzIoniwaTDAD4YNFjBgAeTgEsAbjGgBPeDnQBvbwHcHTigACwAuGAAiYCJ4YBp5Jz8YAGo5eXVVJgiZYJwHLGCocIiAVgUM7JhkIgIsBzAAGT0iyPkcZAiAX06zazsAQUQoEAAlHAgHAC9CXptvGm8YAKDgnLyC2E7TdAsrG1sAISIIHAAVIgAjTz6bZZCfO+DOm5hc-MKfN43nmxsJah8-0gP1+3CgRB8YKIIIA9LMYEwQbYYYNhmMJtMCPDkY4nL1WEA

But if I use the below App.js I am told:
Error: An invalid "width" prop has been specified. Grids must specify a number for width. "undefined" was specified.
validateSharedProps
src/createGridComponent.js:901

Is the playground using a bugfixed unreleased version (I'm using 1.11.3) or am I doing something silly?

Here is the App.js (modified from create-react-app):
```
import React from 'react';

import './App.css';

import BaseTable from 'react-base-table'
import AutoResizer from 'react-base-table'
import 'react-base-table/styles.css'


const generateColumns = (count = 10, prefix = 'column-', props) =>
  new Array(count).fill(0).map((column, columnIndex) => ({
    ...props,
    key: `${prefix}${columnIndex}`,
    dataKey: `${prefix}${columnIndex}`,
    title: `Column ${columnIndex}`,
    width: 150,
  }))

const generateData = (columns, count = 200, prefix = 'row-') =>
  new Array(count).fill(0).map((row, rowIndex) => {
    return columns.reduce(
      (rowData, column, columnIndex) => {
        rowData[column.dataKey] = `Row ${rowIndex} - Col ${columnIndex}`
        return rowData
      },
      {
        id: `${prefix}${rowIndex}`,
        parentId: null,
      }
    )
  })
  
const columns = generateColumns(10)
const data = generateData(columns, 2000)

function App() {
  return (
    <div className="App">
      <div style={{width: "500px", height: "500px", marginLeft: "20em"}}>
        <AutoResizer>
          {({ width, height }) => (
            <BaseTable
              width={width}
              height={height}
              columns={columns} data={data}
            />
          )}
        </AutoResizer>
      </div>
    </div>
  );
}
```

**Comment by nihgwu** [comment]
change `import AutoResizer from 'react-base-table'` to `import { AutoResizer } from 'react-base-table'` should solve the problem

**Comment by jonquark** [comment]
Oops - embarrassing - thank you for so quickly pointing out my mistake!
