### ISSUE TITLE
Question: Context (action) menu 

### ISSUE THREAD

**Issue by bizunas** [Autodesk/react-base-table#244]
How can we achieve context menu (3 dots for actions) on row. 
I saw this example in advanced table image, but can't figure out how to achieve this as my data gets stale if linking data on column in cellRenderer.

**Comment by nihgwu** [comment]
https://github.com/Autodesk/react-base-table#closure-problem-in-custom-renderers

**Comment by bizunas** [comment]
@nihgwu I do not enclose it as a closure from outside.

```
{
    key: 'action',
    width: 40,
    align: Column.Alignment.CENTER,
    frozen: Column.FrozenDirection.RIGHT,
    cellRenderer: ({ rowData, column, rowIndex }) => (
        <div className={styles.menu}>
            <Button
                onClick={() => onMenuClick(column, rowIndex)}
            />
            {column.openMenuRow === rowIndex && (
                <div className={styles['context-menu']} ref={ref}>
                    <li>
                        <Button onClick={() => onRegistrationSelect(rowData, true)} link>
                            <FormattedMessage id="edit" defaultMessage="Edit" />
                        </Button>
                    </li>
                </div>
            )}
        </div>
    ),
}
```


```
function onMenuClick(column, rowIndex) {
    column.openMenuRow = rowIndex;
}
```

But the action cellRendered rerenders only when leaving (blur) cell.

**Comment by bizunas** [comment]
What I actually want to achieve is as in 
![image](https://user-images.githubusercontent.com/147144/97298103-a4265c00-185b-11eb-9c2a-3971fcbb7167.png)

But I can't figure out why cellRenderer renders after exit of cell.

**Comment by nihgwu** [comment]
you should not put the ContextMenu in the cell, the ContextMenu should be shared for the whole table, you can check how it's implemented in Nirvana's MatrixTable
> But the action cellRendered rerenders only when leaving (blur) cell.
BaseTable is optimized to avoid unnecessary re-rendering, here you click the button, but `data|columns|rowClassName` or other props/state didn't changed, so the cell won't re-render, and the context menu won't show, but for fixed table, hovering will trigger the row's re-render, so the menu appears on mouse leaving

**Comment by bizunas** [comment]
Oh ok, I can do for the whole table. Could you link to Nirvana MatrixTable ? I cannot find any package or github or any related information on it.

**Comment by nihgwu** [comment]
@bizunas  That's interesting, I saw you posted the screenshot of Cost Management, so I thought you are a member of that team, I think you can reach out the team for help as well, Nirvana is not a open sourced

**Comment by nihgwu** [comment]
And context menu is a builtin feature in MatrixTable, you can use `actionOptions` to show that, but the action button is at the end of the row, but you can use the same logic to show the action button in other cells

**Comment by bizunas** [comment]
I'm just random guy here :) I got the screenshot from live demos. It just had the thing that I need. 

Thanks for guidance.
