### ISSUE TITLE
表格排序字段的问题

### ISSUE THREAD

**Issue by 52flutter** [Autodesk/react-base-table#245]
SortOrder应该有三个字段一个是正序，逆序和空，这样显示效果会好一些，和antd一样 默认展示排序的箭头，代表可以对字段排序，点击排序的字段一次是正序 逆序 空

**Comment by 52flutter** [comment]
sortState传到SortIndicator中方便控制只对排序字段的显示控制，实际的场景是 多个字段可以排序  但是每次只生效一个，需要讲其他重置到默认状态

**Comment by nihgwu** [comment]
嗯，sortOrder 确实可以再加一个 `None`, 不过其实这个并不重要，因为这个是controlled prop，你完全可以根据当前的order以及上一次order来决定下一个order是什么，https://autodesk.github.io/react-base-table/examples/multi-sort 这个例子就实现了三种状态
sortState可以用来做多字段排序，同样也能做单字段排序，当然在sortState之前是用的sortBy，就是只支持但字段排序，但是感觉这个有局限性，后面会被sortState完全取代

**Comment by 52flutter** [comment]
sorting应该传到SortIndicator中 方便自定义排序图标时候的扩展
