### ISSUE TITLE
Support for frozen columns in non-fixed grids

### ISSUE THREAD

**Issue by jamesonhill** [Autodesk/react-base-table#247]
If you set the `fixed` prop to false & use `flexGrow/Shrink` for column widths, the `column.frozen` definitions are ignored. Is this something that you think the grid should support? If yes, I am willing to attempt to put a PR together for it.

Example: https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDBa3bQYAMwIgAXnlFRemXPmKldRcZUkQZdGQHJ1WvAFoNAdye3WbcCtUBLAA8cTgoqNEwJagA6ZCIABxpzMJlIsABJME4cAKYMAD4YAG8WGBh4HFgHbTASmD9VGCTJDKyAmAAeGDpcqrw+UMkogDENauE-AhxgKD9wKIAZAFEhgBVa+sbUluyYAoAOHtG+zAHUYaOwccnp2bAogCU0gHEACTXSyahEAjAimCiAakZL1fgBfFigrzKWDZOJETKnMAAaRwAE8+LZUk4GLYWCwAPT4mBETicGAQEDIHDkxAAIzqpGQEBYqhABEa5Vgfj4DAA3HUOl0FPy-ABqUW5Yqlbh6KJxRAQAAWNClpX+AJlRAA2gwALpSWqlPycABcMAABgASQqanW6qLG0FOCB0pzWvyg80GtUwOGTMBQNKmmC2vUOzjetVa2HwkIWVAo1G6s3mgDKdJg7s9kchtU1coVytVpQBUVtsn1hrqwatNp4Wor4adLtpbsKHq9Vb9eEDwfL9uNkdK0YCcIR8eRaOTFvT9KzndKuelPALSpVVdL-aH1ZT1v7TedrpbbY72+7AaDu7regbA84zdd8+3I7HcbCienadds8z7eztVzcFvA4GAoEmEQeD4RAwFUeASFIMAaE1LxYTZLgcFUIhEHgWAaFydAChoWp2hWIhaXKKt-CCTh0EKTD4AgHBwR9VIIFoqjgkRCBmLVTVaLAnAIL0HjShBUx2IuUwRJgGNx3fNFaNkt9JETHj8TyFhWCAA

**Comment by nihgwu** [comment]
If the table is not fixed, it can't be scrolled horizontally, how would `frozen` be used in this case?

**Comment by jamesonhill** [comment]
I was imagining that if you set `fixed={false}` you could provide columns such as:
```
const columns = [{ frozen: 'right', width: 200, ...otherProps }, { flexGrow: 2, ...otherProps }, { flexGrow: 1, ...otherProps }]; 
```
In that case I was expecting `columns[0]` to be frozen right with 200 width, then the remaining columns essentially function the same as they do today and occupy the non-frozen width based on their `flexGrow/Shrink` properties.

**Comment by nihgwu** [comment]
In that case, you can simply move the first column to the last and set `flexShrink={false}`

**Comment by jamesonhill** [comment]
Good point. Didn't consider that. I'll close this. Thanks!
