### ISSUE TITLE
Documentation improvement: styles.css requirement

### ISSUE THREAD

**Issue by robbienohra** [Autodesk/react-base-table#256]
It should be made more clear in the documentation that the following import is _required_:

```
import 'react-base-table/styles.css'
```

I.e. that `BaseTable` will not render correctly without the above import.

It's not clear that `BaseTable` will not render correctly "out of the box" without the above style import.

**Comment by nihgwu** [comment]
PR is welcome :p

**Comment by robbienohra** [comment]
@nihgwu least I can do for the fabulous work you all have done with this library! I'll get on it 😉

**Comment by robbienohra** [comment]
Done! Let me know if I should change the phrasing at all. 😊

**Comment by robbienohra** [comment]
It's not really the `styles.css` file per se as much as it is the CSS classes defined in them, lol. So maybe it's better to phrase it to emphasize the classes themselves. Open to feedback!
