### ISSUE TITLE
Support for server side paging / sort?

### ISSUE THREAD

**Issue by geochronology** [Autodesk/react-base-table#257]
I was wondering if react-base-table supports server-side pagination and sort, with some examples or docs you could point to.

(Didn't see a top-level topic on the docs right now so figured I'd ask here. Sorry if this is kind of a basic question.)

**Comment by nihgwu** [comment]
BaseTable simply display the data you provided, no matter it's generated or fetched from backend, what you need to do is just organize your data and pass it to the table, for pagination/sorting, simply apply the new-fetched data
