### ISSUE TITLE
How to use Draggable rows with AutoResizer?

### ISSUE THREAD

**Issue by kumardennis** [Autodesk/react-base-table#261]
Should it be something like this :
`    <DraggableContainer
        getContainer={getContainer}
        getHelperContainer={getHelperContainer}
        useDragHandle
        onSortEnd={handleSortEnd}
      >
        <AutoResizer>
          {({ width, height }) => {
            return (
              <Table
                ref={table}
                data={dataSource}
                columns={columns2}
                rowProps={rowProps}
                width={width}
                fixed={false}
                height={height}
              />
            );
          }}
        </AutoResizer>
      </DraggableContainer>`

`  const getContainer = () => {
    return table.current.getDOMNode().querySelector(".BaseTable__body");
  };

  const getHelperContainer = () => {
    return table.current.getDOMNode().querySelector(".BaseTable__body");
  };`

I get error : `Unhandled Rejection (TypeError): Cannot read property 'ownerDocument' of undefined`

**Comment by nihgwu** [comment]
Try `<AutoResizer> => < DraggableContainer><BaseTable>`

**Comment by kumardennis** [comment]
I tried it before, it didnt show anything

**Comment by nihgwu** [comment]
https://autodesk.github.io/react-base-table/playground#PTAEEsFsAcHsCcAuoDeoDODEEMBGAbAUwGFYA7HcMw+AGgyzyIFEjJCL7MknCAJbGQAmRUAF9QAM3ixIoAOTxC2AMaIAtNxwFC6gBawV8gFAry6ZGi29SFbFRpdGO1oXacGPHQOGiJAXlAAJWU1AGVnIj5DU3NkABF4bABzZJtySmp4UEDrHVtMmgAKIrQVPXB8ISUycQBKHIA+UHLK6o462LILUESUtJc2DmRcyMJXd0QSsoqqmvqmltn2sk6zboSk1N4fEUIcz20owT3ppbb5sQb-Zta5juMunoB1JOhoGgOLAE8iIQA6ITgABuAANjKBQAB3cBCRB6ABcoAALAAGYFQgDcENAekI4GSekQSLRwL02PBT2Qu1EuUQv0IAKBYJxkiIAA8kWRyIRsZCYXDEaAAOz-ACs0HZfNx+MJxNAAEZUaiAKTYnEAMgRCNwhEkCH2KBxkPWiGGSPk8mlkNwCCENHUREk8uRktAQlgiDNQlAAGIVAHre7wOhoPhsN8kQRDABrIN4glEpEAJlRkqDkGw8GSVCRCol7NAAGZ0zixI9IVqDMCaNrdfqlKhjaBbfB7fB1GZ8Agkb6ABwD6XlynrHpBWBQg6lUAxwjfehUe3s+h3Fb0f4bpQ9K6LIo4gA8fW2gzcwxnc-8KFn3wki8I7Mvd-ZYkazf3zNQG-+W8QL+bkMPLYBmOXxCFfSEIIg-caX2YBwMg0B92AI9gP4E4iHgyCUFXGpy0gpDmXgpCUN4CZhlfToqVAGQoQABRkaB0CnNAaIASWEe8FhuUBShxHBkgAOWwdgkXHKFaBxJ8kTYjjl2MK5HhUcN0CYkidAAFV4UB7zNYQmJCVREH+WiAFclFIGAeQoJtIQsbAzQOI1IKEezsCReEQ3+aAGPQQFXIkyFyz4rTAgMtR-hUJR7MIEJJCKSjIWSQhEAKewsina5miciClEQMzag83yjkICKzJqIyksQeIAHkAFkBNge14v+ABHEyaG+MJCCINQECKeR-gAIWwdBCE0nQAH0JttIRvnkTpAorUBKr4bqPngVKHGyQJ4sWbLIVy-LQEK-5itK+Byv+SqavqxrCGatqOq6nrED6gbhtG8aiCm4r5rLJaaPo2BGIOLNkiY7j9tAEB3XIeRkAbSrjtgUBoBG9AqGSY68QgMgzEgTHqInIHGObUdkB0pISYhlpsHwfBqvgEI8vgMgihO7zgd8wGfIWnLkqOqHIS-SnsGpgKEP4oSROCCcJcgqTQDB7mJ3Ypd5fEf6cT0dDCAiJBmGEZjQFgKo1fvehqChc3Cx3SGybid1XIOABtL8Trss0-JwABdB2NlAF2lEgWAayEH2DhcnB-lDfBwBUe7TaEG36AVPnISj7AY7DeP7qtlPQFRehg9Dxl0+xzzRsQMIcDNadM-qLWDo4dtdqhw7WZ4-9ENebB3hoTCEP3ABBEzXpCDGAC8B+7rDpwFeF6ATOUuOaPcEI3xC1KITaslnzeTNGo8YP3jfKt3mhLxO8+MjSmg8M3je8XwdaL-gK+Kl8la1poN+H8fyC5B9aIENkID+nkdagWAaA-+ADB4AMQl9Qgp9N4oHdp-LyPlYEIP5LCeEl4F56GwTg5eRJLykN-CgjeShJDgKKrwYhCDM50JjrXEqmdGEAMkOAdkjJLySDpqNThj8eZcxYaIxiwiEJwSoYhZCQF0h2C2vAhCdROFIVHuPQgU8Z4byQr3fu8BB583LEFcmoA+BUBGBgekfxAQgnBJCfUFBNDgGnnmAAbKWJxGR1BQllEmEUyppRdh7H6IsRYPEeIAJzROlJmbMVB1C2i9LIPMaYpTGBHI7LsJlIDdAOElLI0VSD4Dyd0IoSo1iOwboEIpNBorxFckUXJ+T0D0FTKiapZS2ku1RD7f4BMyDPDwXoA4+ZUSPHvHAJA7o9TYBMvgZAu1uLr0QoPaCVjGhHmxvsD0iB2kmzIPgb40IEAxiYlQKQHJQAhyatw3hYCBH4FGnUJCliKAbO3mNLSrTuiXj+egCQzCUAcOhkRGRnQgA

**Comment by kumardennis** [comment]
`      <Wrapper>
        <AutoResizer>
          {({ width, height }) => (
            <DraggableContainer
              // getContainer={getContainer}
              // getHelperContainer={getHelperContainer}
              useDragHandle
              onSortEnd={handleSortEnd}
            >
              {console.log(width)}
              <Table
                ref={table}
                data={dataSource}
                columns={columns2}
                resizable
                rowProps={rowProps}
                width={width}
                fixed={false}
                height={height}
              />
            </DraggableContainer>
          )}
        </AutoResizer>
      </Wrapper>`

Gave error: ×
Error: An invalid "width" prop has been specified. Grids must specify a number for width. "undefined" was specified.

I actually tried putting actual number as well for width but showed the same error.

**Comment by nihgwu** [comment]
can you provide a demo in the playground as I did?

**Comment by kumardennis** [comment]
Sorry for such late response, the code worked, I just needed to restart the server, prolly it didn't hot update.
