### ISSUE TITLE
Extend BaseTable components prop to support TableRow shape

### ISSUE THREAD

**Issue by alphabetek** [Autodesk/react-base-table#263]
Today `shape` type supports `TableCell` but not `TableRow`, I am looking how to integrate react-base-table (virtualized mode for large data) with [react-table](https://github.com/tannerlinsley/react-table) library, for performance reasons this library requires calling prepareRow before rendering row, I know that react-base-table provides `rowRenderer` to bring our own custom row element, but I think it would be nice to have this feature in case we want to do a small tweak of existing rows before rendering them, and keep default styles and configuration of react-base-table.

**Comment by nihgwu** [comment]
The reason is that internally `TableRow` has a lot of logical so `rowRenderer` actually only customize inner cells, but maybe you can try to use `rowProps.tagName` https://autodesk.github.io/react-base-table/examples/tag-name
