### ISSUE TITLE
Expand row clicking anywhere

### ISSUE THREAD

**Issue by TheLoneRonin** [Autodesk/react-base-table#264]
### Description

Currently, the table only supports being expanded when you click the expand icon column. There should still be an `expandColumnKey` prop. However, we might want to investigate looking into a new `expandRow` prop.

### Ideal Solution

The ideal implementation will have a simple `expandRow` prop that is a `boolean`. The following is an example implementation.

```jsx
<BaseTable
  expandColumnKey={"id"}
  expandRow={true}
/>
```

By enabling `expandRow`. Now, when you click anywhere, the row expands.

**Comment by nihgwu** [comment]
I think you can use `rowEventHandlers` and controlled `expandedRowKeys` to achieve that

**Comment by TheLoneRonin** [comment]
@nihgwu, I see, there should be an example in the documentation for that.

Do you have a snippet I could use as a reference?
Not sure exactly how you'd pass the expandable to `rowEventHandlers`.

**Comment by nihgwu** [comment]
modified from this example https://autodesk.github.io/react-base-table/examples/expand-controlled

https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZizbhoMAGYBLAB45OFKmkwTqAOmREADjXGVJM42ACSYTji1MMAPhgBvFjBh4HFg1AhAALzx-GA01GBsDZ1ctGAAeOQ9QiLw+fUkTADEwyLBhDQIcYCgNcBMAGQBRAoAVaNj4hyS3GG8ADkzinMw81ELB0vLK6tqAJUcAcQAJVoCKqEQCMF8YE12HGSySmABfFmPWZQ4YNwsiFxGwAGkcAE8+AHIHAFoGd6UAen+MCInE4MAgIGQOHBiAARjFSMgICw1CACPEgrANHwGABuGJpGAAVnxGgA1GSPH4AtwoEQTBZEBAABY0akBHa7WlEADaDAAulJogENJwAFwwAAGABIfNy+fyTKLjl8IHCvrKNMdJUKOTBbhUwFBHOKYPKBUrOLqOTybnc9LZUM8XvyJZKAMpwmCa7XW87RbkMpms9kBXYmeWyQXCmKmmVyng8qOWlVq2EanxanUxg14Y2myOK0XWgK2rS3e6Op6vV1Sz3wn3ZgL+mk8IMstkx8OFkuxt2ywsp1XqtMZrO93NGk39hN0pNFzip9WN3tlisOgzO2se9X172Z33Rf2nS6qKAVEQ8PiIMBqeAkUhgGjci43NFcHBqIiIeCwGgedBvHZdhVDXe1dBmEAAHdnQgGQIGCBpy3AzhIJg14IH5PgZhwIgqhMJkcHdOlSBoHl+VYVZgg2LYaBjVJmiIWEghjAJNB0ThWLgKsIHQHx2N0B4IFOPVWzpPjzxwS86RE0S7UrTdXj4+SN0kZ1ZL1FSIOg2DlOQlxtPQl5hK48A0KQ9c+Lw6Yn3eMzoIs+13iYDSOXARyDNQ6CIDIZk7lwKyqhqWz3P01wvKgny-LAXBnNc1YHIANzzRZ7SCAheJ8UNRPAMh4A0YAAGs2RgMIoNEOkZDK50TipLi9XaGgAEIyoq+lgGZDR4E4Q0YAAHz60roLakwOq6nq8BMIIYqgZkMHQTBmFK6jNnqjlGq0iLYKVMBgCQVxaGq14mEo0SzoQqAPPCtDYJoTabowkxNF-QgaBSQCYBSJqFqGoyTrWgIcHgBDwUQsLDNunlw3unSMKq2GXVOs7jl7ZtXP+TxolYY4gA

**Comment by TheLoneRonin** [comment]
Based @nihgwu, thanks for the example!

**Comment by stephannielsen** [comment]
Hei @nihgwu 

I just implemented this as well based on your sample. One issue I am facing now is that the expanding does not work when explicitly clicking the expand icon. You can test in this in your sample as well. Hovering over the icon shows the pointer, but clicking it has no effect. Only clicking anywhere else in the row correctly expands it.

Any idea on how to fix/achieve this?

**Comment by nihgwu** [comment]
@stephannielsen that's because click event is prevented in `ExpandIcon`, you can either implement your own `ExpandIcon` or simply make it `pointer-events: none` (`.BaseTable__expand-icon`)

**Comment by stephannielsen** [comment]
Thanks for the quick reply. Chose `pointer-events: none` for now, fits my needs.
