### ISSUE TITLE
Frozen columns and flex columns in same table

### ISSUE THREAD

**Issue by clbrec** [Autodesk/react-base-table#265]
Is this case currently supported? If yes, any examples?
Basically want to have a frozen column that is fixed to left and spread rest of the columns with flex-grow.
Upon removing `fixed` prop, the frozen column is unfrozen and from my understanding `frozenData` is for frozen rows.

Cheers

**Comment by nihgwu** [comment]
https://github.com/Autodesk/react-base-table/issues/247

**Comment by clbrec** [comment]
> #247

Thanks, tried it but couldn't get it to work.

Example: 
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZm3DQ4lSRAByOAO58A2ixhHjRgN4wAZgRAAvPAC4YAcng4LUJzO0BLTlAAWjnQArAwyFq4AHgDi1tqOYZZRAMr+BN5gANYJMgB0+RLUegwAujAAvlKGJsbmETgxcUHhKWkZ2TCJ+bmFkHp0JV6+AUEKFTLVNTB1UbEg8TB0LQ2p6Vk5MN29EHqygzA+foGLY5WTNTMNcwtLSStt6515BWpFAMz7hyMnDOPnJpdGvNmndIqt2hstq8+gAWT7DY6MX5nEwlADc5xYDQADiACFw3EREPBYDQmBgAHwwGjVAA8ACEiBAcAAVIgAI1cMG4UCI6FMPKI5QOCP5bwUwv8OG8WH8UH5ADYJaoqJB+dstNpygB6CksVhAA

Assuming i provide the columns like this:
```
const columnsNew = [
        { frozen: 'left', width: 150, flexGrow: 0, flexShrink: 0, ...columns[0] },
        { flexGrow: 1, flexShrink: 0, ...columns[1], width: 100 }, 
        { flexGrow: 1, flexShrink: 0, ...columns[2], width: 100 },
        { flexGrow: 1, flexShrink: 0, ...columns[3], width: 100 },
        { flexGrow: 1, flexShrink: 0, ...columns[4], width: 100 },
    ];
```

Was expecting that if the table width is smaller than the combined width of the columns that `columnsNew[0]` would be frozen to the left and the rest of the columns would be scrollable with a width of 100.

If you change the table width to `width={900}`, so that it is bigger than the combined with of all columns `columnsNew[0]` should be unchanged and the rest of the columns occupy the remaining space.

**Comment by nihgwu** [comment]
for flex table(`fixed={false}`) it's not supposed to be horizontally scrollable, so you need to calculate the total width and toggle `fixed` manually

**Comment by clbrec** [comment]
> 
> 
> for flex table(`fixed={false}`) it's not supposed to be horizontally scrollable, so you need to calculate the total width and toggle `fixed` manually

Sounds reasonable. Thanks!
