### ISSUE TITLE
Feature combination

### ISSUE THREAD

**Issue by zorzysty** [Autodesk/react-base-table#266]
I'm sorry, it's just a question, not an actual issue, so feel free to close it, but it would be awesome if before that happens someone could tell me if `react-base-table` is the right library for my use case.

Here's what I need to **combine** (each of the features below must **work together in a single component instance**):
- row virtualization
- dynamic row heights (based on the tallest react component rendered in a cell within a given row)
- sticky columns both on the left and right side
- lazy data fetching with infinite scroll
- dynamic column visibility toggling (by dynamic I mean "keeping scroll position")

Thanks!

**Comment by nihgwu** [comment]
I'd say all the desired features are viable with BaseTable
