### ISSUE TITLE
Dynamic Header Height feature

### ISSUE THREAD

**Issue by clbrec** [Autodesk/react-base-table#268]
`react-base-table` already has support for dynamic row height (https://github.com/Autodesk/react-base-table/pull/170) - thanks for that @jamesonhill @nihgwu. 

Do you have any plans to add dynamic header height in the future?

Use case:
- Using any dynamic content for the header cell makes the required height vary quite a lot. Currently we would have chose the fixed height of the header in a way that fits the header cell with the 'biggest' content, so we avoid overflow. This doesn't take into account that the width of the columns can be dynamic, making the cell require less height and resulting in awkwardly high header when the width of the table/columns dynamically growths.

Open questions:

- Is this already achievable with the current version of react-base-table? If not, any recommendations on how to implement `dynamic header height`?

Cheers

**Comment by nihgwu** [comment]
I think it should be viable from user land although the implementation would be a bit hacky, you can still override the given height for the header and query it's height, and then set to `headerHeight`

**Comment by jamesonhill** [comment]
When we added dynamic row height, I didn't include the header since it's not rendered in a `react-window` grid. It could be patched though using similar approach.
