### ISSUE TITLE
resizing column triggering re-reorder columns event too

### ISSUE THREAD

**Issue by Michael101sh** [Autodesk/react-base-table#269]
Hello,
I am using in ReactSortableHoc to implement re-ordering columns feature and it works. But when I am making resizing, it's also triggering the re-ordering too and make them both.
How can I prevent from the re-ordering to get into action in case of resizing?

**Comment by nihgwu** [comment]
sorry I don't have the full context, but I think it's better to have a drag handle for SortableHoc instead of make the whole title draggable, I guess that would ease your problem

**Comment by Michael101sh** [comment]
Thanks for the answer.
Suddenly I thought of an idea:

I passed the shouldCancelStart parameter to sortableContainer with the following logic:
shouldCancelStart={(e) => {
    const className = e.target.className || "";
    if (className.includes("column-resizer")) return true;
    return false;
}}

and it works like a magic :)

**Comment by Michael101sh** [comment]
Thanks for the answer.
Suddenly I thought of an idea:

I passed the shouldCancelStart parameter to sortableContainer with the following logic:
shouldCancelStart={(e) => {
const className = e.target.className || "";
if (className.includes("column-resizer")) return true;
return false;
}}

and it works like a magic :)

**Comment by Roshdy** [comment]
@Michael101sh how about sharing your snippit of the re-ordering of columns :)

**Comment by Michael101sh** [comment]
`happily!

`const ReactSortableHoc = require('react-sortable-hoc');
const {sortableContainer, sortableElement, sortableHandle} = ReactSortableHoc;
const SortableHeaderRowRenderer = sortableContainer(
    ({className, columns, style}) => (
        <div className={className} role="row" style={style}>
            {React.Children.map(columns, (column, index) => (
                <SortableHeader index={index}>{column}</SortableHeader>
            ))}
        </div>
    ),
);`

**Comment by Roshdy** [comment]
@Michael101sh thanks for sharing. It's inspiring!
