### ISSUE TITLE
Controlled row expand is broken

### ISSUE THREAD

**Issue by mike-lischke** [Autodesk/react-base-table#272]
I'm fighting now for quite some time with a controlled BaseTable and found it not behaving correctly.

Side note: your example here: https://autodesk.github.io/react-base-table/examples/expand-controlled doesn't expand/collapse nodes, but that's probably due to no explicit handling. That's a bit odd, given that this example is supposed to show how to manually handle the row expansion state.

Now to the issue: in my react component I use a tree which is prefilled with a number of nodes (2 levels). The third level shall be added once a second level node is expanded. I added a dummy (loading...) node to show the expansion triangle.

Now I have two approaches to make this work without success:

1) Row expansion is tracked in `onExpandedRowsChanged`, which works:

```typescript
    private handleExpandedRowsChanged = (expandedRowKeys: RowKey[]): void => {
        this.setState({ expanded: expandedRowKeys });
    };
```

Now when I add new child nodes on first expand of a second level node (in `onRowExpand`) these new children are not displayed. Instead the dummy node is still visible. I triple checked my render method is called after loading the new child nodes and the data is correctly passed to the BaseTable. So it's not a data or refresh issue on my side.

2) The second approach doesn't use `onExpandedRowsChanged` at all, but sets the expanded state in `onRowExpand`. This however has the odd outcome that the rows are not updated at all. The expansion triangle toggles as it should, but the nodes show up in the same state as before. That's independent of whether I load new children or not.

I can somewhat make it work by using the first appraoch but when I loaded the children I add the (already expanded) rowKey again to the expanded list. It's there twice after that, but at least it causes the table to refresh. This causes the next collapse call to be ignored however (because of the double key), which I fix by removing that key afterwards unconditionally:

```typescript
                            // Getting the tree to re-render new children we have to use a pretty odd approach.
                            const { expanded } = this.state;

                            // First add the expanded row to the expanded state (it's already there, but do it again).
                            this.setState({ expanded: [...expanded, args.rowKey] });

                            // Then remove the duplicate row key again, to enable the next click to collapse the node
                            // (or it will take 2 clicks).
                            this.setState({ expanded });
```

So in sum it looks as if the internal refresh is broken completely when it comes to row expand/collapse. Also neither `forceUpdate()` nor `forceUpdateTable()` made any difference.

**Comment by nihgwu** [comment]
the controlled example should the next state in the console.log, here is a working example with handler https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZizbhoMAGYBLAB45OFKmkwTqAOmREADjXGVJM42ACSYTji1MMAPhgBvFjBh4HFg1AhAALzx-GA01GBsDZ1ctGAAeOQ9QiLw+fUkTADEwyLBhDQIcYCgNcBMAGQBRAoAVaNj4hyS3GG8ADkzinMw81ELB0vLK6tqAJUcAcQAJVoCKqEQCMF8YE12HGSySmABfFmPWZQ4YNwsiFxGwAGkcAE8+AHIHAFoGd6UAen+MCInE4MAgIGQOHBiAARjFSMgICw1CACPEgrANHwGABuGJpGAAVnxGgA1GSPH4AtwoEQTBZEBAABY0akBHa7WlEADaDAAulJogENJwAFwwAAGABIfNy+fyTKLjl8IHCvrKNMdJUKOTBbhUwFBHOKYPKBUrOLqOTybnc9LZUM8XvyJZKAMpwmCa7XW87RbkMpms9kBXYmeWyQXCmKmmVyng8qOWlVq2EanxanUxg14Y2myOK0XWgK2rS3e6Op6vV1Sz3wn3ZgL+mk8IMstkx8OFkuxt2ywsp1XqtMZrO93NGk39hN0pNFzip9WN3tlisOgzO2se9X172Z33Rf2nS6qKAVEQ8PiIMBqeAkUhgGjci43NFcHBqIiIeCwGgedBvHZdhVDXe1dBmEAAHdnQgGQIGCBpy3AzhIJg14IH5PgZhwIgqhMJkcHdOlSBoHl3jCKCfneflWFWYINi2GgY1SZoiFhIIYwCTQdE4Li4CrCB0B8HjdAeCBTj1Vs6WE88cEvOlJKku1K03V5hJUjdJGdJS9U0iDoNgjTkJcAz0JeCT+PANCkPXYS8OmJ93ms6DbPtd4mF0jlwDc0zUOgiAyGZO5cGEhCoF81x-PMyy9X+TxolYU4gA

**Comment by nihgwu** [comment]
For the first approach, I guess the problem is that you didn't change the ref of `data`, instead of `data[0].children = [...]`, you should do `data = [{...data[0], children: [...], ...]`, it would be great if you can provide a minimal repro example in the playground or codesandbox

**Comment by mike-lischke** [comment]
Thanks for your hint, however, that approach will make things way more complicated. The event handler only passes in the data of the particular row. According to your suggestion I would have to replace the entire row data, which would require to search my large tree structure for that particular entry and replace it. That sounds like an awful performance hog, while all I want is to add new children.

**Comment by nihgwu** [comment]
@mike-lischke mutate object directly without change the ref is always error prone, that's why immutable data library is suggested. the table simply display provided data, and it doesn't know the data is changed if you change internal part directly. `BaseTable` is optimised to avoid unnecessary re-rendering, sometimes it would be annoying

Regarding your concern about performance of searching a large tree, I think it should be fine, I tested with my `unflatten` util and it only costs 50ms to unflatten an 50k array to a tree, so for your case, if you are using `unflatten` you don't need to search the specific row at all, you just need to append new added data to the end and call `unflatten` again

**Comment by nihgwu** [comment]
BTW you don't need to search for the particular row, you can use `onRowExpand({ expanded, rowData, rowIndex, rowKey })` to get the rowIndex

**Comment by mike-lischke** [comment]
About mutation of objects: that's a rather strange idea, given that the entire data is an object. The question is: where do we draw the line what is checked for changes. The tree data is an object with children, which in turn are also objects which children. There's no single line to say: "here's the last checked point, anything below is considered being part of that object, which hence must be replaced as a whole".

When I have an object with a child array then any optimization should always check if the child array has changed, no? You certainly do the check recursively for lower level elements, why not also checking if the children member as such changed?

And for the row index: that doesn't help at all. I have a tree stucture in memory, not a row list. But since I have not thousands of nodes, doing a linear depth-first search for the row key shouldn't take that long. It's just that I feel this is the wrong approach.

Anyway, many thanks for that great component and your effort to help me with my problems!

**Comment by nihgwu** [comment]
In practice we use `seamless-immutable` to enforce immutable mutation, so it's a must to change the whole object, perhaps something like `immer` would help for you case, `rowIndex` would help as it represents the position of current expanded data in the table, so you can find the locate the node to change in O(1), that's `tableRef.getExpandedState().expandedData[rowIndex]`, no matter how deep the node is, it will be in the root level if it's shown in the table
