### ISSUE TITLE
选择性开启虚拟化加载 Turn on Virtualization loading selectively

### ISSUE THREAD

**Issue by Job-Simth** [Autodesk/react-base-table#278]
某些情况下我们页面的数据比较少，这时不一定需要开启虚拟化加载页面。例如页面数据50条，table的窗口显示了30列，这时如果禁用掉虚拟化可以获得较好的页面滚动的体验。

Translated from Google：
In some cases, the data on our page is relatively small, so there is no need to open the virtualized loading page. For example, there are 50 columns of data in the page and 30 columns in the table window. If virtualization is disabled, we can get a better page scrolling experience.

**Comment by nihgwu** [comment]
fair enough, that's also one of the features I planned https://github.com/Autodesk/react-base-table/issues/3

**Comment by Job-Simth** [comment]
Thanks for your answer👍

**Comment by 52flutter** [comment]
you can try
https://52flutter.github.io/react-base-table-extends/
