### ISSUE TITLE
rowID could be number too?

### ISSUE THREAD

**Issue by keremciu** [Autodesk/react-base-table#28]
I know rowID as number is not scalable but some of our data will not gonna be bigger to put as string. yep, in some cases our rowID is just number, I don't want to aggregate my data and make them string for this case, it would be nice to accept number and string for rowID propType.

https://github.com/Autodesk/react-base-table/blob/8a5b1f5c90a04419a04028592d10e4eb140b265d/src/GridTable.js#L171

**Comment by nihgwu** [comment]
yes I think it could be number, I will verify
