### ISSUE TITLE
Fixed header on window scroll

### ISSUE THREAD

**Issue by mobot11** [Autodesk/react-base-table#281]
I'll start by saying this library has been a lifesaver for me! 

I have a somewhat obscure question, do you know of a way to keep the table header fixed as the outer window scrolls? I have a product request for this functionality and am curious if there's a hack or tweak you know of to support this.

Something similar to the "Affix Horizontal Scrollbar" example on http://rsuite.github.io/rsuite-table/

**Comment by nihgwu** [comment]
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZizbhoMAMpQAnvBycAKkQBGOvtG26aB4ziYADFjBgA6AEJEIOKzoD63gBY4RJyEMq7unkY+-oHBBAC0BCAA7jAA3g6OMAAOIBAAllB54ABcMNB5wADWmjAAhHnIOQRQRGBQANwZjlAgWaUMnY4Aviz2LDgAHk1cOABmRIjwsDRMGAB8MDQZADwa5vqROF0ws3kTuscS1OipV5AjmTDcLTfPRA+ZAXlYflA3AJJgU5gAqaD4AejWLFYQA

**Comment by mobot11** [comment]
Thanks!
