### ISSUE TITLE
0 did`t render

### ISSUE THREAD

**Issue by Job-Simth** [Autodesk/react-base-table#283]
This is a JSON [{up datetime: 0}] in the table, this column does not show 0, but an empty cell.
![image](https://user-images.githubusercontent.com/33348656/112284255-00cf5b00-8cc4-11eb-8a31-2c132d1ce0d8.png)
![image](https://user-images.githubusercontent.com/33348656/112284480-40964280-8cc4-11eb-874c-eb5a96ed452e.png)
![image](https://user-images.githubusercontent.com/33348656/112284498-47bd5080-8cc4-11eb-8b56-65d8a9a451fc.png)

I tried to use cellrender: ({celldata}) = > celldata, finally updateTimes showed up, but how it happend?

**Comment by nihgwu** [comment]
do you have custom cellRenderer? I can't reproduce it https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZi25QiAbQYBdVQHIJqALQNtGvgxYscADwAOIAlxwAzIoniwaTDAD4YNFjBgAHgAVIgAjeBwYZSJ0AG8YgF8vfwCYOL1IADpkImtxSklvX1S0oIoqMBgAaxwAT3jMrNq6xPSsjsy2gHoUsqYmRNTA7tCInBTWIA

**Comment by Job-Simth** [comment]
I use react-texty to replace the whole TableCell, which leads to this problem. const TableCell = ({ className, cellData }) => <Text className={className}>{cellData}</Text>; now I use div to wrap the final display content: const TableCell = ({ className, cellData }) => <Text className={className}><div>{cellData}</div></Text>; He can display it normally. At the same time, I notice that you are also a contributor to react-texty. Will this be fixed later?

**Comment by Job-Simth** [comment]
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZi25QiAbQYBdVQHIJqALQNtGvgzbhoMACo4AHrEwAlHEWBQb9gJ4tzHa0QAjeHIceHg+GgBvOHgiCAgAOSJkHBlgUPhRFRgAXyYMAD4YGhYYGAAeD1hgWPiklPRImrjE5JwcgqaMrKIc8oB6KoKWVl9LK0DggAkXTkIyDIjo5rq2tMpJXPz0IpKyyrtq2taGpuP69s69MAA6KABLKGC+wcPh1jsABxACLhwAMyIiHgsBo212pQqEyCOBgyiIjXhOTgIGQ33wYCgEEa0WhwQWYRkeJwMyIcwIBPCOQ6kLKTQ21BuyCIn3EDLAhWKtLKFQoVA5AGscJ5GtcbkLPMjIjcZddkf1hjyYEwmDlIQNie8WEA
you can see this

**Comment by nihgwu** [comment]
yes I can confirm there is a bug in `react-texty` but I'd say please don't use this component as it's unmaintained, use other tooltip component as alternative
