### ISSUE TITLE
Strange div blocks the table

### ISSUE THREAD

**Issue by kumardennis** [Autodesk/react-base-table#292]
strange div with inline styles `style="overflow: visible; height: 0px; width: 0px;"` seems to be laying over, 

If I don't apply these css styles :
`
div[style*="overflow: visible; height: 0px; width: 0px;"] {
    height: auto !important;
    overflow-y: scroll !important;
    width: fit-content !important;
    height: 400px !important;
    z-index: -100;
    &::-webkit-scrollbar {
      width: 0px;
    }
  }
`
then it seems to be hiding the actual table.

**Comment by nihgwu** [comment]
It doesn't matter as it's from `AutoResizer`(react-virtualized-auto-sizer) for resize detecting, you don't need `AutoResizer` if you know the size of you table
