### ISSUE TITLE
Table rows displays incorrect data on scroll

### ISSUE THREAD

**Issue by kumardennis** [Autodesk/react-base-table#293]
The actual dataSource seems to be correct, but when start scrolling, the displayed data inside  the rows starts flickering and shows incorrect rows.
This is with AutoResizer and DraggableContainer setup.

**Comment by nihgwu** [comment]
do you have unique `rowKey` (default to `id`) for each row?

**Comment by kumardennis** [comment]
this is what i have
`
  const Row = ({ key, index, children, ...rest }) => (
    <DraggableElement
      style={{ height: "40px !important" }}
      key={key}
      id={key}
      index={index}
      rowKey={key}
    >
      <div {...rest}>{children}</div>
    </DraggableElement>
  );
`

I am not sure if this is how it should be

**Comment by nihgwu** [comment]
I mean the `data` https://github.com/Autodesk/react-base-table#unique-key

**Comment by kumardennis** [comment]
oh yeah ofcourse, i already had id, but i added rowKey as well, still the same issue

**Comment by kumardennis** [comment]
finally, i had parentID as well set to null there, removed, and it worked.
Thanks !
