### ISSUE TITLE
BUG - Extra Header Cell Placeholder

### ISSUE THREAD

**Issue by abubakir1997** [Autodesk/react-base-table#297]
## System:
 - OS: macOS 11.2.3
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 788.74 MB / 8.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v12.21.0/bin/yarn
 - npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm

## Bug:
I have a weird bug, for some reason this one table adds an extra header cell placeholder in my fixed table. I only have 3 left frozen columns but 4 header placeholders causing the header to body alignment go off.
![Screen Shot 2021-04-23 at 6 46 43 AM](https://user-images.githubusercontent.com/18533628/115861420-c4953480-a400-11eb-9d49-226f28ef00e1.png)
Sometime it works properly and adds 3 header placeholders but most of the time it has 4. My other fixed tables work just fine. Not sure why this is facing this issue. I don't have any conditionally rendered columns.

## Expected Behavior
Table should correctly add only 3 header cell placeholders and not 4.

## Actual Behavior
Table adds 4 cell placeholders and sometimes it correctly does 3.

**Comment by nihgwu** [comment]
Sorry for the late response, do you have any clue on this issue? As you said it works well in other places, so I guess there is something different in this component which trigged the problem

**Comment by abubakir1997** [comment]
It turned out two columns had the same key which caused the issue.
