### ISSUE TITLE
How customize Body of the table

### ISSUE THREAD

**Issue by dohoangtung** [Autodesk/react-base-table#311]
Hi,

I see that I can use component to customize TableCell, but how to customize the Body? I want to warp  Body of the Table with contextMenu.

Thanks,

**Comment by nihgwu** [comment]
you don't need to  you can use Portal to implement context menu, that's what we do internally, like `<><BaseTable rowEventHandlers={{onContextMenu}} /><ContextMenu ref={menuRef} /></>`

**Comment by dohoangtung** [comment]
Thanks for the quick reply. I know that I can do this way but it takes lot of efforts to developing the menu component,  checking mouse pointer position, control trigger area  etc, I'm going to use Dropdown from Ant Design and finding a way to integrate with BaseTable. 

Thanks

**Comment by nihgwu** [comment]
Yes `Dropdown` should be helpful here, you don't need to customise table body

**Comment by dohoangtung** [comment]
Thank you. I've managed to develop the menu without customizing the table body.
