### ISSUE TITLE
rowClassName prop class is not applying

### ISSUE THREAD

**Issue by skyshine999** [Autodesk/react-base-table#319]
I am using rowClassName prop in react base table. Actually i want to show different row background color for particular condition. I am trying to use this prop but it is not working.

const handleRowClass  = ({ rowData, rowIndex }) => {
    if(rowIndex === 1){
      return "table-highlight-row" // class name 
    }
    return ""
  }

**Comment by nihgwu** [comment]
can't reproduce it
![image](https://user-images.githubusercontent.com/2595058/124671987-359ba280-deae-11eb-83cc-fcbcd93ecad4.png)

**Comment by skyshine999** [comment]
yeah my side i gave wrong style, now it is working fine thanks
