### ISSUE TITLE
Changing the default Sort icon

### ISSUE THREAD

**Issue by kaleem-elahi** [Autodesk/react-base-table#327]
Hoe to sort default sort icon and use a custom component in place of that ? @nihgwu

**Comment by kaleem-elahi** [comment]
Closing as there is already a way given in documentation. 

Thanks!

**Comment by mjangir** [comment]
> Closing as there is already a way given in documentation.
> 
> Thanks!

Where did you find that way? I also want to do that. thanks.

**Comment by kaleem-elahi** [comment]
@mjangir just use prop `components` and in that use `SortIndicator`.
```
<Basetable
    components={{
        SortIndicator: CustomSortComponent,
      }}
/>
```
