### ISSUE TITLE
How to enable default sort order in column object

### ISSUE THREAD

**Issue by skyshine999** [Autodesk/react-base-table#345]
I am creating columns array by adding objects.but for one row i need to enable default sort order. I didn't find any sort order prop without clicking on sort arrows.

column = {
          title: itemObj.CNAME,
          dataIndex: itemObj.KEY,
          key: itemObj.KEY,
          align: "right",
          sorter:a[itemObj.KEY].localeCompare(b[itemObj.KEY],
          default sort order ===> asc || desc
}

**Comment by nihgwu** [comment]
there is no sorter in column shapa, use `sortBy` or `sortState` https://autodesk.github.io/react-base-table/api/basetable#props-sortBy
