### ISSUE TITLE
show link in a cell when mouse hover over the row

### ISSUE THREAD

**Issue by murtdagi** [Autodesk/react-base-table#347]
I have a scenario where i have 5 columns in a table.
When the mouse is hovered anywhere on the row, i want to make the 3rd column a link for the user to be able to click and launch out. I am unable to figure out how can i achieve this?
any thoughts @nihgwu

**Comment by nihgwu** [comment]
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlANwBQoksAJiURtjyESOACJ8aCFJAA0MAEwNm7NjgAeABxAEeOAGZFE8WDSYYAfDADebGHHDQYAbQAWIAG6Ec3AEogA7gDSOACechA4UAASHl6+AcEhALoCPjhEwFAAdIgRAMpQIjRgRvCsbLb2XPbwEKnpmTkRALI4yCA0phbWlXYAlnowNACEbp4E3n5BoWYTUIgEYDXSEOx2dnMLS1LUWchEGp0Icn3camboljbr6wNDp2oww+iYAMyzkVs1azcwm4s9X7rLIg469X7AHDweBpMDcLwEABcQysfwC4kKckh0Ix-AAvhcruCgf8lgR0XwsqcMC8YGM4lNEjAAPwwADkMXG3jZMGR2PguJ+QLxMmJMDxQvF5TsIuc9Im8WmyXKlVJQ3BAB4ACpEABG8BwYr6WDA2hwADFEGBMn1wABJMAUKiOkDIDRECboKwGWo4PFivR9NTeMU7SBehAQf1A3iFL2xojR37k-wAUU8YGiRDhBoIEC91yBMHAzRAuRwqczhGRNFRKaZBO6EWisQVjNCNHrM1FReLYGaAHlywAZdKeGuEmDNzkMhIdkrQpg9354pN2AD05kq5QlbCAA

**Comment by murtdagi** [comment]
Excellent, thanks a lot
