### ISSUE TITLE
Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by JacobCutshall** [Autodesk/react-base-table#349]
- EDIT: I didn't fix the issue but found a way to work around it. I can set the sections under react-bootstrap Tabs component to mountOnEnter. I avoided this because it will cause the device to lag a little when clicking on an un-rendered tab/ unMounted Component.
---
I have a page that has four separate sections. Each of these sections is a react-bootstrap Tab containing a react-base-table (using estimated row height for dynamic rows) in each of them. If I don't click on each tab and show each sections table before I switch to another page I get `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.` and `[Violation] `setTimeout` handler took <N>ms`. I am throttling the CPU because this application is going on a hardware limited device. I have a hacky solution. After the data loads for that page I will loop through each section to render that table. But this is not a good way too handle this problem. when I look at the page elements the DOM nodes are there with the data before that section has shown, but the problem goes away if I show all tables before clicking to another page. Any suggestions will help. I do also have the react-base-table wrapped in a wrapper component shown below.
```
import BaseTable, { Column } from "react-base-table";
import "react-base-table/styles.css";
import "../../Styles/WindowTableWrapper/WindowTableWrapper.scss";

interface Props {
	columns: any;
	data: any;
	sortBy?: any;
	onColumnSort?: any;
}

const WindowTableWrapper = ({ columns, data, sortBy, onColumnSort }: Props) => {
	return (
		<BaseTable
			width={855}
			maxHeight={600}
			data={data}
			sortBy={sortBy}
			onColumnSort={onColumnSort}
			estimatedRowHeight={49}
			headerClassName={"window-table__header"}
			rowClassName={"window-table__row"}
			className='window-table'
			overscanRowCount={3}
		>
			{columns.map((col) => (
				<Column
					className={"window-table__cell"}
					headerClassName={"window-table__header-cell"}
					key={col.key}
					{...col}
				/>
			))}
		</BaseTable>
	);
};

export default WindowTableWrapper;

```

- also would love to know how I am supposed to override the base css.
- What I tried - import it into my wrapper component
- what I haven't tried - setting the classPrefix to AdvanceTable
```
$table-prefix: AdvanceTable;

$table-font-size: 16px;
$table-padding-left: 15px;
$table-padding-right: 25px;
$column-padding: 7.5px;
$show-frozen-rows-shadow: false;
$show-frozen-columns-shadow: true;

@import "~react-base-table/es/_BaseTable.scss";

.#{$table-prefix} {
	&:not(.#{$table-prefix}--show-left-shadow) {
		.#{$table-prefix}__table-frozen-left {
			box-shadow: none;
		}
	}

	&:not(.#{$table-prefix}--show-right-shadow) {
		.#{$table-prefix}__table-frozen-right {
			box-shadow: none;
		}
	}
}

```

**Comment by nihgwu** [comment]
You can just ignore the warning, in React v18 this warning is removed
Regarding the style overriding, follow the guideline to provide your style variables
