### ISSUE TITLE
How to highlight /change background color of selectedRow?

### ISSUE THREAD

**Issue by ElixirMike** [Autodesk/react-base-table#350]
I've been trying to use the examples provided to do this, but I don't have/use styled components and what I want to do is change the background color of the row which has just been selected. I store the row in a state variable, but where/how do I use this to change color?

I think the rowProps is the right place, but what exactly do I return when calling rowProps? For example, if I wanted to change row 1, I tried returning the className that has this, but that doesn't work.  How to do it?

```
  const rowProps = ({ rowIndex }) => {
      if(rowIndex ===1) {
          return "quickview"
      }
      return "";
  }
```

**Comment by ElixirMike** [comment]
found solution.

**Comment by sklinov** [comment]
@ElixirMike Could you please share the details on your solution?
