### ISSUE TITLE
How to change the zIndex in Header to allow Dropdown list of actions?

### ISSUE THREAD

**Issue by ElixirMike** [Autodesk/react-base-table#351]
I'm trying to add a dropdown list of actions in the header. The issue is that I can't seem to change the zIndex so that the dropdown options appear on top. I am using the headerRenderer to change the header and specify the dropdown . I wrap it in a Div and specify the zIndex, but this is not working. 

How would I get the dropdown list of actions to properly appear on the top?

![image](https://user-images.githubusercontent.com/34098742/147572215-8d934d87-a108-4607-bebb-8fb880b476a3.png)

const getHeader = (field,header) => (
 <Dropdown>
    <Dropdown.Menu>
    <Dropdown.Item
        onClick={() => columnAction('filter', field,header)}
        icon="filter"
        text="Apply search filter"
      />
      <Dropdown.Item
        onClick={() => columnAction('asc', field,header)}
        icon="sort content ascending"
        text="Sort ascending"
      />
      <Dropdown.Item
        onClick={() => columnAction('desc', field,header)}
        icon="sort content descending"
        text="Sort descending"
      />
      <Dropdown.Item
        onClick={() => columnAction('hide',field,header)}
        icon="eye slash"
        text="Hide column"
      />
    </Dropdown.Menu>
  </Dropdown>
)

Here is where I use the headerRenderer

`  columns.push({key:col.data, resizable: true, width:200,title:col.header,dataKey:'CustomID', frozen: Column.FrozenDirection.LEFT,cellRenderer: ({ rowData}) =>(<div style={{cursor:'pointer',color:`${color}`}} onClick={() => showDetail(rowData[col.data])}>🔎 {rowData['CustomID']}</div>), headerRenderer: () => <div style={{position:'relative',zIndex:30}} >Record {getHeader(col.data,col.header)}</div> })`

**Comment by nihgwu** [comment]
zIndex won't work in this case as there is `overflow: hidden`, you should use `Portal` (like popper.js) to render it outside of table

**Comment by nihgwu** [comment]
https://github.com/Autodesk/react-base-table/issues/116#issuecomment-553220764

**Comment by ElixirMike** [comment]
Any chance you have an example of how to do this?
