### ISSUE TITLE
Dynamic table height without scroll

### ISSUE THREAD

**Issue by conchau** [Autodesk/react-base-table#353]
I've tried using the AutoResizer to make a table that expands vertically to fit the data, but since a height value is required to render the data in the table, the whole table becomes scrollable once it reaches the min-height value.

Instead, I need the table to expand in height to fit the data instead of the overflow data becoming scrollable. 

Here is what I have:

    const Container = styled.div`
        min-height: 500px;
    `
    
        <Container>
          <AutoResizer>
            {({ width, height }) => (
                <BaseTable 
                    className={l.questionTable} 
                    ref={refContainer} 
                    columns={columns} 
                    data={tableData} 
                    fixed={false} 
                    width={width} 
                    height={height} 
                    headerHeight={0} 
                    rowHeight={60}
                />
            )}
          </AutoResizer>
        </Container>

I tried following suggestions in #108 to no avail.

How can I achieve this?

**Comment by nihgwu** [comment]
As I explained in the linked issue, in this case you just need to set `maxHeight={Infinity}` and that's all, `AutoSizer` is used to measure the parent container's size so the table can fit in it, but now you don't need that, you don't need to use it at all or, you can only use it to measure the width by `disableHeight`

**Comment by conchau** [comment]
> As I explained in the linked issue, in this case you just need to set `maxHeight={Infinity}` and that's all, `AutoSizer` is used to measure the parent container's size so the table can fit in it, but now you don't need that, you don't need to use it at all or, you can only use it to measure the width by `disableHeight`

I have tried this by removing the AutoResizer, setting a fixed width and height, and adding `maxHeight={Infinity}` but that cuts off the table.

**Comment by nihgwu** [comment]
@conchau makes no sense, can you share a example via https://autodesk.github.io/react-base-table/playground
[demo](https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDBa3bQYAMwIgAXnlFRemXPmKldRcZUkQZdGQHJ1WvAFoNAdye3WbcCtUBLAA8cTgoqNEwJagA6ZCIABxpzMJlIsABJME4cAKYMAD4YAG8WGBh4HFgHbTASmD9VGCTJDKyAmAAeGDpcqrw+UMkogDENauE-AhxgKD9wKIAZAFEhgBVa+sbUluyYAoAOHtG+zAHUYaOwccnp2bAogCU0gHEACTXSyahEAjAimCiAakZL1fgBfFigrzKWDZOJETKnMAAaRwAE8+LZUk4GLYWCwAPT4mBETicGAQEDIHDkxAAIzqpGQEBYqhABEa5Vgfj4DAA3HUOl0FPy-ABqUW5Yqlbh6KJxRAQAAWNClpX+AJlRAA2gwALpSWqlPycABcMAABgASQqanW6qLG0FOCB0pzWvyg80GtUwOGTMBQNKmmC2vUOzjetVa2HwkIWVAo1G6s3mgDKdJg7s9kchtU1coVytVpQBUVtsn1hrqwatNp4Wor4adLtpbsKHq9Vb9eEDwfL9uNkdK0YCcIR8eRaOTFvT9KzndKuelPALSpVVdL-aH1ZT1v7TedrpbbY72+7AaDu7regbA84zdd8+3I7HcbCienadds8z7eztVzcFvA4GAoEmEQeD4RAwFUeASFIMAaE1LxYTZLgcFUIhEHgWAaFydAChoWp2hWIhaXKKt-CCTgq1SCB0EKKjgkRCBwR9TUGLAnAIL0Ni1RBUwGIEng+NKGNx3fNEGPEt9JETUSYFiAIXhwPwsEVKAGIyfwwD8KBUT4-E8hYVggA) scrolling doesn't work well as the container uses flex center, and it's a know issue for flex layout, but `maxHeight` works

**Comment by conchau** [comment]
> @conchau makes no sense, can you share a example via https://autodesk.github.io/react-base-table/playground [demo](https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDBa3bQYAMwIgAXnlFRemXPmKldRcZUkQZdGQHJ1WvAFoNAdye3WbcCtUBLAA8cTgoqNEwJagA6ZCIABxpzMJlIsABJME4cAKYMAD4YAG8WGBh4HFgHbTASmD9VGCTJDKyAmAAeGDpcqrw+UMkogDENauE-AhxgKD9wKIAZAFEhgBVa+sbUluyYAoAOHtG+zAHUYaOwccnp2bAogCU0gHEACTXSyahEAjAimCiAakZL1fgBfFigrzKWDZOJETKnMAAaRwAE8+LZUk4GLYWCwAPT4mBETicGAQEDIHDkxAAIzqpGQEBYqhABEa5Vgfj4DAA3HUOl0FPy-ABqUW5Yqlbh6KJxRAQAAWNClpX+AJlRAA2gwALpSWqlPycABcMAABgASQqanW6qLG0FOCB0pzWvyg80GtUwOGTMBQNKmmC2vUOzjetVa2HwkIWVAo1G6s3mgDKdJg7s9kchtU1coVytVpQBUVtsn1hrqwatNp4Wor4adLtpbsKHq9Vb9eEDwfL9uNkdK0YCcIR8eRaOTFvT9KzndKuelPALSpVVdL-aH1ZT1v7TedrpbbY72+7AaDu7regbA84zdd8+3I7HcbCienadds8z7eztVzcFvA4GAoEmEQeD4RAwFUeASFIMAaE1LxYTZLgcFUIhEHgWAaFydAChoWp2hWIhaXKKt-CCTgq1SCB0EKKjgkRCBwR9TUGLAnAIL0Ni1RBUwGIEng+NKGNx3fNEGPEt9JETUSYFiAIXhwPwsEVKAGIyfwwD8KBUT4-E8hYVggA) scrolling doesn't work well as the container uses flex center, and it's a know issue for flex layout, but `maxHeight` works

I resolved my issue by setting a min-height on the parent div, removing the AutoResizer, and using `maxHeight={Infinity}` instead of providing a height. Thanks!
