### ISSUE TITLE
Force rerender of column when props change

### ISSUE THREAD

**Issue by conchau** [Autodesk/react-base-table#354]
I'm providing a value via props from a parent component to a child component that contains my BaseTable. The value that is passed down is successfully rendered in one of the columns via the cellRenderer.

The issue is that whenever the value is updated in the parent component, the value that is passed to my table via props is not forcing the Column to rerender. I have confirmed the child component is successfully receiving the updated value through rendering the value in a h1 tag outside of my BaseTable.

How can I get the updated value to render inside of the Column of the BaseTable?

**Comment by gansong99** [comment]
Hello, how did you finally solve this problem? Thank you very much!
