### ISSUE TITLE
table doesnt show correctly

### ISSUE THREAD

**Issue by dil12321** [Autodesk/react-base-table#364]
this doesn't work at all
<img width="750" alt="Screen Shot 2022-02-28 at 2 08 28 pm" src="https://user-images.githubusercontent.com/30675549/155917663-f2c037fc-f553-491e-83d1-2c5adbe33aa6.png">

**Comment by jamesonhill** [comment]
Did you import the lib css?

**Comment by dil12321** [comment]
Thanks, this worked
