### ISSUE TITLE
How to use scrollToRow on functional component load?

### ISSUE THREAD

**Issue by ElixirMike** [Autodesk/react-base-table#367]
I'm using a functional component and trying to use the scrollToRow method when the component loads.
It works fine if I have it triggered from button click, etc, but for some reason, I cannot get it to work when component/table first is loaded.

In the useEffect, I do all the logic to create/load the data, and then call the scrollToRow method, but it isnt' working.

What is the best way to have this work using a functional component? IS there any method that designates the table is loaded/complete?

` 
 useEffect(() => {
    setActiveData(data);
    setIsLoading(true);
    setCols([]);
    loadColumns();
    tableRef.current.scrollToRow(20,'auto');   
 },[data,rowHeight])

 return (

    <BaseTable 
        ref={tableRef}
        onColumnResizeEnd={onColumnResize} 
        onScroll={scrollUpdate}
        rowKey="id" 
        rowClassName={rowProps}
        sortBy={sortBy}
        onColumnSort={sortResults}
        fixed 
        rowHeight={rowHeight} 
        columns={isLoading ? [] : cols} 
        data={activeData} 
        width={window.innerWidth-265} 
        height={window.innerHeight-160} />
   
  );`

**Comment by nihgwu** [comment]
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZixY4AHgAcQBLjgBmRRPFg0mGAHwwYAbxYX20GFCIAjeDgBKuvh6LAoAOkQId10aMAN4VltwewBteCIALwBPUUcZIKgAGUSUngBdLxwff0CcAGVHUhoYvMiYGxhvXwCggFEdHRxfGmMzKwaLDOzk1KIabkc6qMhKHD94ECwaAHIASRgAd3AAHWXYRDUJnBgIJLBgeCTlmXiRnimYAHpHhwALAEsITfA974IAaxgRC+jhcxwmvE+MBwyDUUCSAwczlcHh0fmAiAIBDw-ggwAIlHgABUQG4QBt6Ao6gBfGQ1OoNJolNodLpQHomdDmawWQY4LI5Ubje6I265RzzPBYKCvGAAMjlcGis3mixW6ywIH2hyEnBgr0IOGuMDFoweoJRunRmOxYFx+MJJLJFMYigstJgcUF+VYDWxUExYBgNERAB4icjjtidOhLBbgjpqUqqJBYxJqEmIbHTTwk49TA1WNSWEA
check out the console log you will understand
