### ISSUE TITLE
fluid column width

### ISSUE THREAD

**Issue by keremciu** [Autodesk/react-base-table#37]
Right now I'm always passing a width to every column, if I don't pass, I couldn't see it on table.

I think we can just have a prop called `defaultColumnWidth` then we can just use it while we're calculating column width.

```js
  getColumnWidth(column, key) {
    const {
      isFluid,
      defaultColumnWidth,
      initialColumnWidths,
    } = this.props;
    const baseWidth = 20;

    if (isFluid) {
      return initialColumnWidths[column.key] || column.width || (baseWidth + (column.title.length * 10));
    }

    return initialColumnWidths[column.key] || column.width || defaultColumnWidth;
  }
```

this function will gonna make a variable called `calculatedColumns` after aggregating all columns. We can use it inside this functionality:

```js
export function adjustColumnWidths(calculatedColumns, calculatedColumnsWidth, expectedWidth) {
  if (expectedWidth > totalWidth) {
    return distributeWidth(columns, expectedWidth - calculatedColumnsWidth);
  }
  return columns;
}

function distributeWidth(columns, _remainingWidth) {
  const newColumns = [];
  let remainingWidth = _remainingWidth;
  const perColumnWidth = remainingWidth / columns.length;

  columns.forEach(column => {
    const newColumnWidth = Math.floor(column.width + perColumnWidth);
    remainingWidth -= perColumnWidth;
    newColumns.push({
      ...column,
      width: newColumnWidth,
    });
  });

  return newColumns;
}
```

This whole functionality will give us a chance to pass columns without `width` key.

In my project, we've a toggle column feature and sometimes we're showing only 1 or 2 columns, it would be nice to have this fluid functionality to spread them into whole table.

**Comment by nihgwu** [comment]
Hi, thanks for your detailed description, have you saw the screenshot of our internal table component built on BaseTable, we implemented the column toggling feature too

actually BaseTable supports flexible columns by default, so you only need to calculate if the total width is larger than the table, if so you set `fixed={true}`, or you could set to `fixed={false}` and then all the columns are flexible based on the flex layout, and the flex width is automatically based on `flex: {flexGrow} {flexShrink} {width}`, so if it's flexible, you could set all the columns' width to be `0` or any number and `flexGrow={1}`, or some with `flexGrow={2}`

**Comment by keremciu** [comment]
hi @nihgwu Thanks for detailed answer too :) I saw the case but I'm not sure about why I can't use fixed and fluid columns together?

If I don't provide width prop for column then it's giving an error:

```Warning: Failed prop type: The prop `columns[1].width` is marked as required in `BaseTable`, but its value is `undefined`.
in BaseTable (created by DataTable)```

yep yep, I'm calculating the column width if the total width is larger than the table as you can as a condition in my code: 
```if (expectedWidth > totalWidth) {```

I think we can put this functionality inside base-table cause it could be a common case; using fixed and fluid columns together.

**Comment by nihgwu** [comment]
fluid column could be only available in **Flex Mode**(`fixed=false`), and it's available in by default, in **Fixed Mode** `flexGrow=0` `flexShrink=0` and could not be changed, in `Flex Mode`, by default `flexGrow=0`, `flexShrink=1`, you could set `flexShrink=0` to make this column's width is fixed, if it's flexible, the width is not so important you could even set it to `0`, so you you don't like `width` to be `required`, you could give it a default value in your `DataTable`, create your own `Column` and set `defaultProps`

I didn't make the `Auto Mode` builtin as in some case the users just want to keep in `Fixed Mode` even there are empty space, and that's not hard to implement from user land, and `BaseTable` is designed to be unopinionated, we could support that via plugins in the future

**Comment by keremciu** [comment]
@nihgwu I got your point now, yep maybe I need to put this functionality in a different repository as `react-base-table-fluid` then we can just make it as a plugin to base-table.

we can define a minWidth for the default cause when user put 0 width for column then there's no way to see it on the screen.

I will try to make this ready then we can talk about on that like is there any disadvantage or a problem maybe
