### ISSUE TITLE
rowspan supported?

### ISSUE THREAD

**Issue by dingchaoyan1983** [Autodesk/react-base-table#4]
does row span is supported? I find the clospan is supported in the example.

**Comment by nihgwu** [comment]
That's a good question, I think you could use the same technique as colspan, for example add extra style to the cell you want to extend
```
    background: red;
    height: 100px;
    align-self: flex-start;
    z-index: 1;
```
![image](https://user-images.githubusercontent.com/2595058/56080418-7f15f800-5e33-11e9-8006-1c594a2c6bf8.png)
if you want to overlap the space above, use `align-self: flex-end` and `z-index` could be removed

**Comment by nihgwu** [comment]
I will add a example for that later, thanks

**Comment by nihgwu** [comment]
Just tested with a real example and it doesn't work so well because of virtualization, I tried to use `overscanCount` to workaround but only one side is over rendered, but `react-window` renders on both side, I'll update the example when I switch to `react-window`
