### ISSUE TITLE
Make the  custom expand icon easier ?

### ISSUE THREAD

**Issue by NexxLuo** [Autodesk/react-base-table#40]
I want to custom the expand icon styles ， but i found it is very difficult. Because when i use the
table components  to reset expandIcon component ,i have to handle the onExpand event.
I just want to set the expand icon display styles,  only use  css or  custom component easily.

**Comment by nihgwu** [comment]
Sorry it's not supported, the builtin expandIcon is supposed to be override by the consumers to implement their own tables

**Comment by NexxLuo** [comment]
of course  , but the override way must let the consumers make the expandedRowKeys  controled ?Is it necessary ?

**Comment by nihgwu** [comment]
nope, there is nothing to do with `expandedRowKeys`, you could still `defaultExpandedRowKeys`

**Comment by NexxLuo** [comment]
Sorry, it`s my fault. I found the right way to use table components ExpandIcon,like this :

`const ExpandIcon = props => {
    let { expandable, expanded, onExpand } = props;

    let cls = "table__expandicon";

    if (expandable === false) {
        return null;
    }

    if (expanded === true) {
        cls += " expanded";
    }

    return (
        <span
            className={cls}
            onClick={() => {
                onExpand(!expanded);
            }}
        />
    );
};
`

Maybe you can describe it clearly in the document.
