### ISSUE TITLE
Why am I experiencing scroll delay in my implementation when it looks smooth in the playground example

### ISSUE THREAD

**Issue by anhdd-kuro** [Autodesk/react-base-table#408]
[Playground](https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDBa3bQYAMwIgAXnlFRemXPmKldRcZUkQZdGQHJ1WvAFoNAdye3WbcCtUBLAA8cTgoqNEwJagA6ZCIABxpzMJlIsABJME4cAKYMAD4YAG8WGBh4HFgHbTASmD9VGCTJDKyAmAAeGDpcqrw+UMkogDENauE-AhxgKD9wKIAZAFEhgBVa+sbUluyYAoAOHtG+zAHUYaOwccnp2bAogCU0gHEACTXSyahEAjAimCiAakZL1fgBfFigrzKWDZOJETKnMAAaRwAE8+LZUk4GLYWCwAPT4mBETicGAQEDIHDkxAAIzqpGQEBYqhABEa5Vgfj4DAA3HUOl0FPy-ABqUW5Yqlbh6KJxRAQAAWNClpX+AJlRAA2gwALpSWqlPycABcMAABgASQqanW6qLG0FOCB0pzWvyg80GtUwOGTMBQNKmmC2vUOzjetVa2HwkIWVAo1G6s3mgDKdJg7s9kchtU1coVytVpQBUVtsn1hrqwatNp4Wor4adLtpbsKHq9Vb9eEDwfL9uNkdK0YCcIR8eRaOTFvT9KzndKuelPALSpVVdL-aH1ZT1v7TedrpbbY72+7AaDu7regbA84zdd8+3I7HcbCienadds8z7eztVzcFvA4GAoEmEQeD4RAwFUeASFIMAaE1LxYTZLgcFUIhEHgWAaFydAChoWp2hWIhaXKKt-CCTgq1SCB0EKKjgkRCBwR9TUGLAnAIL0Ni1RBUwGIEng+NKGNx3fNEGPEt9JETUSYEVHA-CwRUoAYvYFAU1xjSgRUGMYLTanxPIWFYIA)

[Mine](https://playcode.io/1323592)

As you can see, there is a slight lag ( or delay ? ) between the frozen part and the main part when their scroll is synced. 
However, I don't understand why I can't see any lag in the playground. 
I have tried using different versions of this library and React, but the result remains the same. 
What could be causing this

https://user-images.githubusercontent.com/13819766/226239086-9f67f3ea-cd53-4cfc-b4f2-d9ff1a207306.mov

**Comment by Uregek** [comment]
@anhdd-kuro did you find a solution?

**Comment by anhdd-kuro** [comment]
@Uregek 
I thought this repo was no longer maintained so I decided to give up on using it
I end up with solution using react-window and custom to add sticky column on it
