### ISSUE TITLE
Scroll lag  when using frozen columns

### ISSUE THREAD

**Issue by NexxLuo** [Autodesk/react-base-table#41]
I use a table with frozen columns , it is not just-in-time  when i scroll. Is it a bug from react-window ?
but there is a example doesn`t have this problem in document :
https://autodesk.github.io/react-base-table/examples/expand-icon-props

there is my demo code
https://codesandbox.io/s/dazzling-ardinghelli-xo1yh?fontsize=14

How can i solve it ?

**Comment by nihgwu** [comment]
What's the browser you are testing against? I can't see any lag with your demo in Chrome, another possibility is that the provided example is in production env while yours is in develop env, and try to avoid printing large data in your renderers

**Comment by nihgwu** [comment]
The gif explained the issue well, so I guess the problem would be relaxed a bit in `production` mode, I've tried my best to make the lag neglectable but it's really a hard task
