### ISSUE TITLE
is it possible to make a column autoResize its width?

### ISSUE THREAD

**Issue by tadeuqc** [Autodesk/react-base-table#43]
I want to add an empty column with auto width to fill in blank space and separate data from columns with actions to make it nicer to the eyes. Is it possible?

**Comment by nihgwu** [comment]
set `flexGrow: 1, flexShrink: 0, align: Alignment.RIGHT, frozen: FrozenDirection.RIGHT` would be enough, and that's what we do in internal table for action column, in this way it works both in flex and fixed mode

**Comment by nihgwu** [comment]
related topic #37
