### ISSUE TITLE
Create multi header easier ?

### ISSUE THREAD

**Issue by NexxLuo** [Autodesk/react-base-table#44]
The currenty way to create multi header like this: https://autodesk.github.io/react-base-table/examples/multi-header.
I`v to say it is not simple.

The simple way maybe like this ,just use the children attribute.

![image](https://user-images.githubusercontent.com/18549980/59021122-d0fc5c80-887d-11e9-98ce-bf803309b27b.png)

**Comment by nihgwu** [comment]
I’d say BaseTable is not recommended to be used directly, you could implement a easier version on you own table component based on the current api, I’ll share our internal implementation of column groups later

**Comment by nihgwu** [comment]
BTW, here is our API for that
```
  /**
   * The groups for the columns
   */
  columnGroups: PropTypes.arrayOf(
    PropTypes.shape({
      key: PropTypes.string.isRequired,
      title: PropTypes.string.isRequired,
      parentKey: PropTypes.string,
    })
  ),
```

**Comment by NexxLuo** [comment]
Could  you share a complete example ？ thanks a lot

**Comment by nihgwu** [comment]
I'm working on the new demo system right now #21 , will do after that

**Comment by eokoneyo** [comment]
@nihgwu Any chance you might be able to share the demo for column groups? I'd find it really helpful

**Comment by nihgwu** [comment]
I didn't check the implementation but looks good https://github.com/Autodesk/react-base-table/issues/252#issuecomment-801777317

**Comment by eokoneyo** [comment]
I also saw that, I'm just a little apprehensive that `react-base-table` isn't used as a dependency especially considering the project name.

**Comment by sklinov** [comment]
> BTW, here is our API for that
> 
> ```
>   /**
>    * The groups for the columns
>    */
>   columnGroups: PropTypes.arrayOf(
>     PropTypes.shape({
>       key: PropTypes.string.isRequired,
>       title: PropTypes.string.isRequired,
>       parentKey: PropTypes.string,
>     })
>   ),
> ```

@nihgwu I believe this API doesn't exist anymore? I couldn't find it in any relevant place in the codebase.
Also the example in the documentation looks outdated, because now there's not such prop as `cells` in `headerRenderer`
What is the type of object `headerRenderer` expected to return in order to have grouped header? A nested array of `React.Node`s?

**Comment by sklinov** [comment]
Ok, I think I've figured it out!
For ones of you (@eokoneyo , @NexxLuo ) who are struggling with docs and can't find a working example here's a Sandbox with 2 options for `headerRenderer`.
Note that there are 2 of them with different signatures (one in `<BaseTable >` and one in `<Column>` components).
The `headerHeight` prop in `<BaseTable>` is the one that defines the number of levels in header, so if it's a plain number - then it's a regular header, if it's an array of numbers, then it's a multi header.

https://codesandbox.io/s/react-base-table-multi-header-4xh7d?file=/src/App.tsx
