### ISSUE TITLE
Add an argument for headerRenderer to flag it is 'frozen left' or 'frozen right'

### ISSUE THREAD

**Issue by NexxLuo** [Autodesk/react-base-table#49]
I use headerRenderer  to custom the table header. And there are some frozen columns. 
I want to render different element in left columns and right columns, but i can`t know which frozen type  is it.

Shall you add a parameter to flag it ? like this :
 ` headerRenderer = (cells, columns, headerIndex, frozen)=>{}`

**Comment by nihgwu** [comment]
check my point https://github.com/Autodesk/react-base-table/issues/25#issuecomment-490073764

**Comment by NexxLuo** [comment]
It`s very useful,thanks.
