### ISSUE TITLE
ColumnResizer indicator line incorrect

### ISSUE THREAD

**Issue by NexxLuo** [Autodesk/react-base-table#50]
The resizer  indicator line position will be  incorrect when using right frozen columns and drag too much.

gif below:

![TEST](https://user-images.githubusercontent.com/18549980/59321354-45168480-8d04-11e9-96b6-ad4e564d28f6.gif)

BTW. How to custom resizer indicator style , something like width 、maxWidth

**Comment by NexxLuo** [comment]
sorry , my fault . I should  set the column maxWidth

**Comment by nihgwu** [comment]
![image](https://user-images.githubusercontent.com/2595058/59326270-a0eb0880-8d18-11e9-9adc-e07d7aff055b.png)
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDABMDZm3DQYAMwIgAXnlFRemXPmKldRcZUkQZdGQHJ1WvAFoNAdye3WSjmoCWADxxOCio0TAlqADpkIgAHGnNQmQiwAEkwThx-JgwAPhgAbxYYGHgcWAdtMGKYX1UYRMl0zP8YAB45HMq8PhDJSIAxDSrhXwIcYChfcEiAGQBRAYAVGrqGlOasmHyANi7hnsw+1EGDsFHxyemwSIAlVIBxAAkVkvGoRAIwQphIv5SZK5fJwoAALABcMEYDBk3TAMnGEF8miIACMypCoAREDgYABfFh4rzsFRZWJEDLHMAAaRwAE8+LYUk4GLYWCwAPQcmBETicGAQEDIXEQRCo2qkZAQFiqEAEBplWC+PgMADctXaMAAzOrfABqPU5Iolbh6SKxRAQUE0Y0lX5-U1EADaDAAulIaiVgZCAAYAEgKjpdrsiwLxTlFqKcAd8eJ9HrtMHJ4zAUFSnEhQbdoc4CbtTrJFOCFlQtLprt9AGUxTAY3G80Sao7zZbrbaSn9IkHZO7PbUMzB-YGeE6eznw5HowVY-G+8m8GmB92Q8C8yUC-5yZSSzT6RXB9XxXXZyVGyaeC2rTa+53l2v+76A8vxxGxa+o8f7-PU+nH8O9KOK6cBOb6fn2G5bsWoRlvuPqHk4h61tO9Y1I2BLeCoWI4CIPB8IgYCqPAJCkGANCOl4ZJylwOCqEQiDwLANA5Og+Q0DUbRLGiZR9qoARBH2KQQOgBS8YEUGWASiaOsJWE4Xokl2nCpjCUpPAKSUhbbtB9LCZp4mlvS6kwOAVK3DgSLaMJRBXOANC2CZO5mRZOCeApHK5CwrBAA
I can reproduce the issue with this code, wanna send a PR to fix it? 

I admit the current behavior is weird for right frozen column resizing, I thought about it before, but if we place the indicator to left, it would be to close to the one in the normal column

**Comment by nihgwu** [comment]
I will give it a try to place the indicator left to see which one is better
BTW, your table looks cool, that's exactly what I'd love to see to consume `BaseTable`

**Comment by NexxLuo** [comment]
version 1.3.2 . 
Any breaking changes ? My headerRender rendered incorrectly  when updated to the lates version.

![image](https://user-images.githubusercontent.com/18549980/59477249-f3e2ce00-8e86-11e9-94fc-77d9d023ee41.png)

**Comment by nihgwu** [comment]
Nope, you can see the change is minor comparing to previous version

**Comment by NexxLuo** [comment]
yes, it`s a problem from my table.
BTW .  The resizing behavior about forzen right columns ,maybe should be same as the left columns.
The resizing line still move left from right by drag.
