### ISSUE TITLE
Expand lag in develop env

### ISSUE THREAD

**Issue by NexxLuo** [Autodesk/react-base-table#52]
Expand lag in develop env but not appear in production mode .It cost about 20 seconds when i expand a row in 10000 rows table.

**Comment by nihgwu** [comment]
That's interesting, I remember it only take less then 30ms to unflatten 30000 rows, and I just tested locally and there is no lag, so I guess there should be something wrong on your side
here is the code I'm using (I'm running it locally):
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDEYN5rdtBgAzAiABeeUVF6Zc+YqR1FxlSRBl0ZAcjWa8AWnUB3RzdZtwylQEsAHjicFFRomBLUAHTIRAAONGahMhFgAJJgnDj+TBgAfDAA3iwwMPA4sPZaYMUwviowiZLpmf4wADwwAEw5lXh8IZKRAGLqVcK+BDjAUL7gkQAyAKJDACo1dQ0pzVkw+QAcPaN9mAOow0dg45PTs2CRAEqpAOIAEmslk1CIBGCFMJEAlIyXq-AC+LFBniUsCysSIGVOYAA0jgAJ58GwpRwMGwsFgAenxMCInE4MAgIGQOHJiAARrVSMgICwVCACA0yrBfHwGABuWrtWTyeT83wAajFOSKJW4ukisUQEAAFjRpSV-gDZUQANoMAC6UhqJV8nAAXDAAAYAEgKWt1esiJtBjggdMcNt8oIthvVMDhkzAUFSZpgdv1js4PvV2th8OC5lQKNRevNFoAynSYB6vVHITUtfLFSq1SUAZE7Z0DUbaiHrbaeNrKxHna7ae6Cp7vdX-XggyGKw6TVGSjH-HCEQnkWiU5aM-Ts12SnmZTxC8rVdWywPhzXUzaB82XW7W+3Ozue4Hg3v67pG4POC23Qud6Px-HQkmZ+m3XOsx2czUebgl4HAwFAkwiDwfCIGAKjwCQpBgDQWqeLCbJcDgKhEIg8CwDQOToPkNA1G0KxELSZTVn4gScNWKQQOgBTUUEiIQOCvpaox4E4JBujseqIImIxgk8PxJSxhOH5ooxEnvpISb8fiuQsKwQA
