### ISSUE TITLE
Additional Features - In-place edit & filter rows

### ISSUE THREAD

**Issue by devshell** [Autodesk/react-base-table#62]
Any chance in-place edit and filtering in headers will be added as hooks?
I would especially love to see in-place edit with support for excel like formulas.

**Comment by k00p** [comment]
The search/filtering behavior here in the [redux sematable component](https://github.com/sematext/sematable) would be the tipping point for me to use this component.

**Comment by nihgwu** [comment]
We have much complex inline editing behaviors in internal products, I'll there the feature with recipes, or support that with plugin, but it won't be builtin the component itself, I don't won't to restrict the use cases

**Comment by devshell** [comment]
So is there another git-hub repo where we can list the plug-ins?

**Comment by nihgwu** [comment]
@devshell the plugins will be in this repo too, managed by lerna

**Comment by nihgwu** [comment]
Just wrote something about Inline Editing
https://autodesk.github.io/react-base-table/docs/inline-editing
https://autodesk.github.io/react-base-table/examples/inline-editing

**Comment by devshell** [comment]
@nihgwu you rock! Thanks for the great example !!  Any chance you can also add an example for the column filtering?

**Comment by nihgwu** [comment]
Tracking this one #64
