### ISSUE TITLE
Dragable Row

### ISSUE THREAD

**Issue by atilkan** [Autodesk/react-base-table#66]
Dragable Row example resets data order on drag end.

**Comment by nihgwu** [comment]
You would find that there is no state there, that's just for demo concept proof, not really use case, I would make it more completed when I have enough time on that, or contribution is well welcome

**Comment by atilkan** [comment]
@nihgwu A note would be informative on it.

**Comment by nihgwu** [comment]
I will complete the example later, and improve the ui

**Comment by nihgwu** [comment]
Btw right now I’m working on reorganizing the examples to be more accessible

**Comment by atilkan** [comment]
@nihgwu Does it mean a vuejs port maybe? That would be lovely.

**Comment by nihgwu** [comment]
the example has been updated, and I don't use Vue, maybe someone else could help on that
