### ISSUE TITLE
Multi Column Sorting 

### ISSUE THREAD

**Issue by ghost** [Autodesk/react-base-table#67]
I expected columns to be numbered accordingly. 
https://autodesk.github.io/react-base-table/examples/multi-sort

**Comment by nihgwu** [comment]
the `column.key` should be string, not sure what you needed, please provide more detailed information, or a reproducible demo in the playground if it's a bug

Sequenced number is not safe for columns as some of them could be hidden, the `columnIndex` will be re-indexed

**Comment by atilkan** [comment]
@nihgwu You should not close issues if you ask for more details. It doesn't mean it resolved. 
An example here. You click column with cmd/ctrl and see what is the order.
https://www.ag-grid.com/example.php#/

**Comment by nihgwu** [comment]
Sorry I thought I've answered your question, now I understand what you expected here, but TBH it won't be implemented in that component, that could be achieved on the consumer side via `Column.headerRenderer`, you will find that the `sortState` does nothing data sorting logic but only define the state of the sort indicators, that means the api just provide the possibilities for the consumers to implement their own logic and behaviors
BTW thank you for the example for multi sort behavior, actually we don't use multi sort internally, but that behavior is inspirational for own potential use case

**Comment by atilkan** [comment]
@nihgwu Thank you.
