### ISSUE TITLE
sortOrder 默认是SortOrder.ASC 能否默认undefined

### ISSUE THREAD

**Issue by Nokecy** [Autodesk/react-base-table#68]
https://github.com/Autodesk/react-base-table/blob/1a20d85c07a8ddefb406072c6e218f954834b445/src/BaseTable.js#L370

**Comment by nihgwu** [comment]
if it's undefined, there won't be sort indicator when hovering on the header, that'b by design, if the column is ordering, then the value is the current order, or it's the next possible order
