### ISSUE TITLE
when Browser resize ， i think we should recall getScrollbarSize ant update state.scrollbarSize.

### ISSUE THREAD

**Issue by yanguoyu** [Autodesk/react-base-table#70]
when Browser resize, the scrollbarSize will change.so i think we should update state.scrollbarSize.
![image](https://user-images.githubusercontent.com/12881040/61866594-09c4c380-af08-11e9-950a-3b3fa198bf2e.png)

**Comment by yanguoyu** [comment]
![image](https://user-images.githubusercontent.com/12881040/61866665-282abf00-af08-11e9-9fdb-5a09fe0e943a.png)

**Comment by nihgwu** [comment]
What's the OS you are testing against? I tested on MacOS and it's 15 constantly, also I don't why the scrollbar size would change on window resizing

**Comment by yanguoyu** [comment]
![image](https://user-images.githubusercontent.com/12881040/61919049-81393800-af86-11e9-82c9-d71febe3f59a.png)
![image](https://user-images.githubusercontent.com/12881040/61919132-c9585a80-af86-11e9-8871-2c4013d2106b.png)
do you allow the scrollbar always show? if you don't allow, the scrollbar size is always zero.

**Comment by yanguoyu** [comment]
do you allow the scrollbar always show? if you don't allow, the scrollbar size is always zero.
![image](https://user-images.githubusercontent.com/12881040/61919220-2fdd7880-af87-11e9-9bb5-51160f6e08f7.png)
![image](https://user-images.githubusercontent.com/12881040/61919231-3cfa6780-af87-11e9-9489-b361441c54c9.png)

**Comment by nihgwu** [comment]
@yanguoyu sure, that's why I got the value `15`

**Comment by yanguoyu** [comment]
my Browser is Chrome and the version is 75
![image](https://user-images.githubusercontent.com/12881040/61919689-556b8180-af89-11e9-89af-4138061dc955.png)

**Comment by yanguoyu** [comment]
https://stackblitz.com/edit/react-1kzp6m

**Comment by yanguoyu** [comment]
Here is my demo.   https://stackblitz.com/edit/react-1kzp6m
![image](https://user-images.githubusercontent.com/12881040/61919868-1984ec00-af8a-11e9-8964-f2de610d8833.png)

**Comment by yanguoyu** [comment]
@nihgwu

**Comment by nihgwu** [comment]
My results 
![image](https://user-images.githubusercontent.com/2595058/61920197-569dae00-af8b-11e9-8620-15cb827f788d.png)

**Comment by yanguoyu** [comment]
@nihgwu What is your browser and What is your browser version?

**Comment by nihgwu** [comment]
![image](https://user-images.githubusercontent.com/2595058/61920499-68338580-af8c-11e9-9830-1d2377441f10.png)

**Comment by yanguoyu** [comment]
it feels weird. now i don't know why we are difference.

**Comment by nihgwu** [comment]
I’m going to close this issue as I think it would be an issue for a lot of libraries as well if it is the case you described

**Comment by yanguoyu** [comment]
ok
