### ISSUE TITLE
Column key 属性是必填

### ISSUE THREAD

**Issue by Nokecy** [Autodesk/react-base-table#71]
https://github.com/Autodesk/react-base-table/blob/1a20d85c07a8ddefb406072c6e218f954834b445/src/utils.js#L21
如果没有填写key 能不能默认用dataKey

**Comment by nihgwu** [comment]
Actually `dataKey` is not required, you could use `dataGetter` as well, and `key` is the single source of truth for referring a column, if you want to use `dataKey` as a fallback, you could implement your own `normalizeColumns` to do that
