### ISSUE TITLE
Spreadsheet like editing

### ISSUE THREAD

**Issue by eiso** [Autodesk/react-base-table#72]
This looks like an amazing project with great performance. Congratulations! I wanted to ask: Are there any plans to add spreadsheet like functionality for making all cells editable?

**Comment by nihgwu** [comment]
It's intended to not include inline editing in `BaseTable`, internally we have advanced inline editing feature based on `BaseTable`, but it's too coupled with ui components, so you can implement excel like editing experience with the current api on your side
I'll provide more examples on this feature when I have enough time on that, hope that would be helpful

**Comment by nihgwu** [comment]
let's track inline editing in #64 , close this one for now
