### ISSUE TITLE
scrollToRow broken in 1.7.0

### ISSUE THREAD

**Issue by hannaofsweden** [Autodesk/react-base-table#76]
As of version 1.7.0 scrollToRow no longer works.

The issue seems to be the scrollToLeft statement that was added last in the scrollToRow function.

This statement resets the horizontal scrolling position to what it was before the method was called.

**Comment by nihgwu** [comment]
hey @hannaofsweden what do you mean by saying `broken`, I tested and `scrollToRow` still work, but I guess you want to keep the horizontal scroll as the previous value, correct?
The reason I reset the horizontal scroll is that if you use `end` or `center` as the second arg, the horizontal scroll will be set to end or center accordingly, which should be not expected, so I reset the horizontal position, but I think I should keep the previous value, WDYT?

**Comment by nihgwu** [comment]
fixed in v1.7.1
