### ISSUE TITLE
Performance issue: When hovering any row triggers headerRenderer and cellRenderer for each column.

### ISSUE THREAD

**Issue by johnpittman** [Autodesk/react-base-table#8]
When hovering any row triggers headerRenderer and cellRenderer for each column.

Test:
put console.log in inside the callbacks and move mouse around.

**Comment by nihgwu** [comment]
Does that impact the performance heavily and is a bottle neck for you? I didn’t on purpose as I noticed some bugs if I make the TableHeader a pure component, like with selection, the checkbox won’t update it’s state when selection state changes, I have to find a solution for that before I make it a pure component, thank you for reminding me that

**Comment by nihgwu** [comment]
Aha, it's another problem, fixing it
