### ISSUE TITLE
Key? What I'm doing wrong?

### ISSUE THREAD

**Issue by rodgarcialima** [Autodesk/react-base-table#87]
Why react is still complaining about the key?
![image](https://user-images.githubusercontent.com/1371488/64477001-305f5680-d164-11e9-9076-a2de95e57d20.png)

Great work btw, thx

**Comment by nihgwu** [comment]
what's the warning? does your data has unique key for each row? the default rowKey is `id`, but you can custom it

**Comment by rodgarcialima** [comment]
The error message is the default react missing key. For this table, the primary key is **usuario_id**, not **id**. I didn't know that **rowKey** existed.

I'll try that. Thank you.

**Comment by eAmin** [comment]
I have the same issue, to clarify the issue, i'll put the relevant error below:
```
Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in div (created by Grid)
    in div (created by Grid)
    in Grid (created by GridTable)
   ...
```

And this is my implementation code:
```javascript
const columns = [
  {
    width: 100,
    title: 'title1',
    dataKey: 't1',
    key: 't1',
  },
  {
    width: 300,
    title: 'title2',
    dataKey: 't2',
    key: 't2',
  },
  // ...
];


<BaseTable
  width={width}
  height={height}
  columns={columns}
  data={rows}
  disabled={state.loading}
  loadingMore={state.loadingMore}
  onEndReachedThreshold={300}
  onEndReached={handleEndReached}
  overlayRenderer={renderOverlay}
  emptyRenderer={renderEmpty}
  headerRenderer={headerRenderer}
  components={{ TableCell: TableCelll }}
  useIsScrolling
  getScrollbarSize={()=>10}
></BaseTable>
```

**Comment by nihgwu** [comment]
hey @eAmin I think you have the same problem with @rodgarcialima , that you have an unique key for each row, the default key is `id`, so it assumes you have the data in the format like `[{id: 0, ...}, {id: 1, ...}]`, I will update the README to mention about that
