### ISSUE TITLE
Question : best practice for changing table theme color dynamically

### ISSUE THREAD

**Issue by x4080** [Autodesk/react-base-table#88]
Hi, what is the best practice for changing table theme color dynamically (example for light or dark theme) since the documentation only mention using scss

Thanks

**Comment by nihgwu** [comment]
if you are using normal stylesheet:
normal `<Table className="Table Table--light" />`
dark `<Table className="Table Table--dark" />`

if you are using `styled-components`:
```
const darkStyle = css`
  .BaseTable__row {}
  .BaseTable__cell {}
`

const StyledTable = styled(BaseTable)`
${props => props.theme === 'dark'? darkStyle: lightStyle}
```

**Comment by x4080** [comment]
Thanks @nihgwu
