### ISSUE TITLE
Question : roweventhandlers, do you have working example beside in the website ?

### ISSUE THREAD

**Issue by x4080** [Autodesk/react-base-table#89]
Hi, basead on the example I added rowEventHandlers  with console.log and it only run when the page is loaded, and nothing happened when row is clicked

```
const rowEventHandlers = {
    onClick: console.log('clicked'),
    
  }
...
<BaseTable ... rowEventHandlers={rowEventHandlers} />
```

And based on your example 
```
const rowEventHandlers = {
  onClick: action('click'),
  onDoubleClick: action('double click'),
  onContextMenu: action('context menu'),
  onMouseEnter: action('mouse enter'),
  onMouseLeave: action('mouse leave'),
}
```

How to get the event, because it only passed string ?

Thanks

**Comment by nihgwu** [comment]
the source code for `action`: `const action = message => args => console.log(message, args)`, it returns a callback actually, so you should use it in this way
```
const rowEventHandlers = {
    onClick: ({ rowData, rowIndex, rowKey, event }) => console.log('clicked'),
    
  }
...
<BaseTable ... rowEventHandlers={rowEventHandlers} />
```

**Comment by x4080** [comment]
Thanks @nihgwu

**Comment by x4080** [comment]
Oh, I didnt know if there's example folder inside the git, no wonder I feel at lost :)

Thanks again

**Comment by nihgwu** [comment]
You are welcome 😄

**Comment by x4080** [comment]
@nihgwu Is it possible to get the column that clicked using this roweventhandlers ? Or there's another event handler to use ?

TIA

**Comment by nihgwu** [comment]
for cells you can just add event listeners on your cell element, like `cellRenderer = () => <div onClick={} />`, or there is an advanced prop `cellProps` to attach listeners on cell's root element

**Comment by x4080** [comment]
Yes, I already do that, I hope there's already some feature in it :)

Thanks again

**Comment by kaleem-elahi** [comment]
I have RowHandler to call a function onClick of row and also a menu popup in cell to open menu on click... now what happens when i click on menuPopover in cell, RowHandler events are fired, I don't know where i have to add Stoppropaate to stop propagation or is there a different way to handle this ?

**Comment by nihgwu** [comment]
@kaleem-elahi that's how React Portal work, it will propagate events to it's host(there is a long discussion on this behaviour in React's repo) , so you need to stopPropagation in your popover
