### ISSUE TITLE
Custom Table and Column

### ISSUE THREAD

**Issue by rodgarcialima** [Autodesk/react-base-table#91]
Hey guys, I'm trying to write a wrapper for Table and Column, but I don't know what's wrong.

This is my Table component wrapper:
![image](https://user-images.githubusercontent.com/1371488/64660308-ba7e1800-d40d-11e9-94ea-20a87ac01864.png)

This is my Column component wrapper:
![image](https://user-images.githubusercontent.com/1371488/64660399-1cd71880-d40e-11e9-8933-73da35ab3190.png)

This is where I'm using it:
![image](https://user-images.githubusercontent.com/1371488/64660733-bce17180-d40f-11e9-864b-600a008c51c9.png)

This is how it's being rendered:
![image](https://user-images.githubusercontent.com/1371488/64660885-4f821080-d410-11e9-9440-8df2068c79b1.png)

This is how it should be rendered:
![image](https://user-images.githubusercontent.com/1371488/64660907-6d4f7580-d410-11e9-82f5-364f2546814d.png)

The weird part is that the console.log on Column component is not printing anything.

Am I doing anything wrong? This is the right way to do this?

Thank you,

Rod

**Comment by nihgwu** [comment]
hey @rodgarcialima `Column` is not a real component actually, it's just a syntax sugar to provide the column definition, so your purpose to use `dataKey` as `key` in that way won't work, the `key` is required for column definition

**Comment by nihgwu** [comment]
BTW, for your table wrapper, you don't need `autoWidth` or `autoHeight` actually, for `AutoResizer`, if you don't provide `width` or `height`, then it will measure the dimension, so it's auto
```
const Table = ({ width, height, ...rest }) => (
  <AutoResizer width={width} height={height}>
    {({ width, height }) => <BaseTable width={width} height={height} {...rest} />}
  </AutoResizer>
```

**Comment by rodgarcialima** [comment]
> hey @rodgarcialima `Column` is not a real component actually, it's just a syntax sugar to provide the column definition, so your purpose to use `dataKey` as `key` in that way won't work, the `key` is required for column definition https://github.com/Autodesk/react-base-table/blob/master/src/utils.js#L16-L18

Thank you for your quick answer @nihgwu.

I got what did you mean about Column, but what I'm not undestanding is the `key/dataKey` relation. There is no mention to `key` on [API](https://autodesk.github.io/react-base-table/api/column), and my table only shows the header and the rows if I use bot `key` and `dataKey`.

**Comment by nihgwu** [comment]
I'm sorry about the confusion and lack of documentation, I'll update the document to mention about the importance of `key` for `Column` later.

I understand your intention to use `dataKey` as `key`, but it's not possible in that way, what I can think about is implement your own `normalizeColumns` https://github.com/Autodesk/react-base-table/blob/master/src/BaseTable.js#L32 to reuse the `dataKey` as `key`. But I'd say it's not recommended, as sometimes we have nested data structure, like `dataKey="user.name"`, or we want to share the same dataKey in multiple columns, but with different `dataGetter` or `cellRenderer`

**Comment by nihgwu** [comment]
I'm wondering if we should provide a `columnsNormalizer` for easier mapping, like we could just use index as key with that prop

**Comment by oytuntez** [comment]
@nihgwu 

> sometimes we have nested data structure, like dataKey="user.name",

fiiihuu, I was almost diving into `dataGetter` to implement nested data keys. Do you mind adding this to the docs? (I would do it myself if it were a bigger update as I don't have a ready to use fork yet)

**Comment by nihgwu** [comment]
@oytuntez it's already mentioned in the doc https://autodesk.github.io/react-base-table/api/column#props-dataKey

**Comment by oytuntez** [comment]
I couldn't find whether the key would support nested keys with dot notation

thanks @nihgwu
