### ISSUE TITLE
Consider Adding an onEndColumnResize prop to <BaseTable />

### ISSUE THREAD

**Issue by nickytonline** [Autodesk/react-base-table#94]
We're starting to use react-base-table on Shotgun. One of the things we're working on is saving column sizes after resizing them. We have this functionality in our current grid, but need to port this functionality to our new grid that is using `<BaseTable />`. The `BaseTable` component has an `onColumnResize` prop, but in our case, we really only want to save settings once the column is finished resizing. I have a PR that adds an `onEndColumnResize` prop to `<BaseTable />` for columns that are resizable.

Is this something you would consider adding to `<BaseTable />`?

**Comment by nihgwu** [comment]
Hi @nickytonline I think you can just throttle the `onColumnResize` to implement that? I'll consider about it more.
BTW if you have any further questions on BaseTable, feel free to ping me on Slack 😁

**Comment by nihgwu** [comment]
I'm vary discreet on adding new props to bloat the API unless it's really needed.
We use debounce to save the width state in MatrixTable `this._storeColumnsState = debounce(this._storeColumnsState, 250);`, so I think you can just use throttle here

**Comment by nickytonline** [comment]
At the moment, I am throttling using `onColumnResize`, but since `<BaseTable />` is using `<ColumnResizer />`, why not allow the developer to tap into `<ColumnResizer />`'s `onResizeStop` via `_handleColumnResizeStop`?

https://github.com/Autodesk/react-base-table/blob/master/src/BaseTable.js#L440

Then there is no throttling required as it's the end of the drag. Thanks again for all your work on this and I may ping you on Slack tomorrow ;)

**Comment by nihgwu** [comment]
I agree with your requirement on the resize end callback, but problem is that we may have to add the resize start callback accordingly in the future, and I think `onColumnResize` is similar to `onScroll`, we don't have `onScrollStart` and `onScrollEnd` either, as we can detect them via `onScroll`

**Comment by nihgwu** [comment]
included in v1.9.0
