### ISSUE TITLE
Auto column width?

### ISSUE THREAD

**Issue by Frekansapp** [Autodesk/react-base-table#96]
Could you consider implementing auto column width or using percentage?

**Comment by nihgwu** [comment]
It's already supported, use `flexGrow`/`flexShrink`, it's only available for `fixed=false`
https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAEwCUAUKJLACYlEbZ6Ek4AIlxoIUkADQw6ABjnMWlcRADaMgLoA6AO4BLdlAAW6GYqqQ1WgGbwcADwDiBENvQBGJmeUq3WvQeNTMWofa1tHZ1c6T3sABxACDhwrIkR4WBoGDAA+GBomGBgAHgAVIgAjWzglanQAb2DIAF8YTigieraiFoB6bKZmIA

Maybe I should add an example for this case later

**Comment by kaleem-elahi** [comment]
yes please add an example @nihgwu  Thanks
