### ISSUE TITLE
Inefficient when adding items to the beginning of data

### ISSUE THREAD

**Issue by florian-bd** [Autodesk/react-base-table#99]
Check:
https://codesandbox.io/embed/goofy-chatelet-xi4h4

I have one item in the table, one cell. 
In the console, `render` is logged once.
I add another item after 5 sec. 
In the console, `render` is logged twice.
All the CellRenderer are recreated and rerendered.

## Issue
When adding items from the start of data `[newItem, ...data]`, the table recreates all the visible cells. It should still only create the one that is added.

## Expected
Should behave like `[...data, newItem]`

**Comment by nihgwu** [comment]
Hi @florian-bd I think that's true for virtualized rendering, if you append the item it works as your expectation, but if you inset to the beginning, the following items would be re-rendered as well as the `style` is changed, that's the `top` for positioning, for your expected list example, they only change the item data, but here we also changed the style of all the rows

**Comment by florian-bd** [comment]
I don't mind re rendering, indeed it can be necessary for some style, but the elements should not be recreated? In that case it re creates them completely. Meaning any state is lost.

**Comment by nihgwu** [comment]
the cell is not recreated, see https://codesandbox.io/embed/goofy-chatelet-xi4h4, in your example it's a function component, so it will be recalled every time, but it doesn't mean it's re-created, if it's recreated, it should be reset to `1` when re-rendered in my example

**Comment by florian-bd** [comment]
Indeed! My bug must be coming from somewhere else... Sorry for the wrong assumption

**Comment by florian-bd** [comment]
Actually the thing is that I implemented my own rowRenderer it's just a wrapper div rendering cells. When I remove it, I get the expected behavior.
However, I don't manage to reproduce in the code sandbox.
Strange

**Comment by nihgwu** [comment]
@florian-bd the cells will be recreated if they are out of table window(unmount) and back again(mount) on scroll

**Comment by nihgwu** [comment]
why do you need an div wrapper for rows?

**Comment by florian-bd** [comment]
yes this makes sense, I have the issue for visible cells. Let me investigate more :)

**Comment by florian-bd** [comment]
> why do you need an div wrapper for rows?

I apply some style on the row depending on some conditions. In the codesandbox it works fine with a custom rowRenderer but not in my App. Even if I just return the cells parameter. Have to figure out why.

**Comment by nihgwu** [comment]
I don't think you have to use extra wrapper for that, you can use `rowClassName` as a function for that https://autodesk.github.io/react-base-table/api/basetable#props-rowClassName, or you can use a `tagName` for `rowProps` for more complex use cases, see https://autodesk.github.io/react-base-table/examples/extra-props https://autodesk.github.io/react-base-table/examples/tag-name

**Comment by nihgwu** [comment]
BTW, I suspect you are changing the id of each row when adding item, which will cause cells being recreated

**Comment by florian-bd** [comment]
> I don't think you have to use extra wrapper for that, you can use `rowClassName` as a function for that https://autodesk.github.io/react-base-table/api/basetable#props-rowClassName, or you can use a `tagName` for `rowProps` for more complex use cases, see https://autodesk.github.io/react-base-table/examples/extra-props https://autodesk.github.io/react-base-table/examples/tag-name

This makes sense but I am using mobx so it's easier if I have an observer component it just rerenders automatically

**Comment by florian-bd** [comment]
> BTW, I suspect you are changing the id of each row when adding item, which will cause cells being recreated

I thought so too, and I was indeed, but when I fixed it, it didn't solve this issue.

**Comment by florian-bd** [comment]
Man the issue is when declaring rowRenderer inline!!!

**Comment by nihgwu** [comment]
Cool, thanks for the investigation

**Comment by florian-bd** [comment]
No problem, thanks for your help.
Here is the repo https://codesandbox.io/s/jovial-stallman-eoeyf

**Comment by nihgwu** [comment]
that demo is really helpful, thanks, now I got it
Because now it take the renderer as a component instead of a pure function, see https://github.com/Autodesk/react-base-table/pull/80, so the inline function actually creating a new component every time it's called, before that the renderer is considered as a pure function instead of a component, but the hooks change the game, that's open this issue for now, I have to figure out a way to fix it

**Comment by pocesar** [comment]
always either use `useCallback` or `useMemo` when passing props that are either objects, arrays or functions to components... this is almost a non-issue on non "stateless function components" (aka classic class component approach)

**Comment by nihgwu** [comment]
@pocesar but I'd say consumers trend to use inline function for renderers, although my recommendation is defining shareable renderers outside of the table component, but the current pattern doesn't forbid inline function, so it's a real issue

**Comment by nihgwu** [comment]
fixed in v1.9.1
